.ubuntu2004:
    image: ${REGISTRY}/build:ubuntu2004
build/ubuntu2004/serial:
    extends: [".build",".ubuntu2004"]
build/ubuntu2004/openmp:
    extends: [".build",".ubuntu2004"]
build/ubuntu2004/mpi:
    extends: [".build",".ubuntu2004"]
build/ubuntu2004/hybrid:
    extends: [".build",".ubuntu2004"]
test/ubuntu2004/serial/serial:
    extends: [".test",".ubuntu2004"]
    needs: ["build/ubuntu2004/serial"]
test/ubuntu2004/openmp/serial:
    extends: [".test",".ubuntu2004"]
    needs: ["build/ubuntu2004/openmp"]
test/ubuntu2004/openmp/openmp:
    extends: [".test",".ubuntu2004"]
    needs: ["build/ubuntu2004/openmp"]
test/ubuntu2004/mpi/serial:
    extends: [".test",".ubuntu2004"]
    needs: ["build/ubuntu2004/mpi"]
test/ubuntu2004/mpi/mpi:
    extends: [".test",".ubuntu2004"]
    needs: ["build/ubuntu2004/mpi"]
test/ubuntu2004/hybrid/serial:
    extends: [".test",".ubuntu2004"]
    needs: ["build/ubuntu2004/hybrid"]
test/ubuntu2004/hybrid/openmp:
    extends: [".test",".ubuntu2004"]
    needs: ["build/ubuntu2004/hybrid"]
test/ubuntu2004/hybrid/mpi:
    extends: [".test",".ubuntu2004"]
    needs: ["build/ubuntu2004/hybrid"]
test/ubuntu2004/hybrid/hybrid:
    extends: [".test",".ubuntu2004"]
    needs: ["build/ubuntu2004/hybrid"]
    tags: ["saas-linux-medium-amd64"]
deb/ubuntu2004/hybrid:
    needs: ["build/ubuntu2004/hybrid"]
    extends: [".deb",".ubuntu2004"]
deb/ubuntu2004/mpi:
    needs: ["build/ubuntu2004/mpi"]
    extends: [".deb",".ubuntu2004"]
deb/ubuntu2004/openmp:
    needs: ["build/ubuntu2004/openmp"]
    extends: [".deb",".ubuntu2004"]
deb/ubuntu2004/serial:
    needs: ["build/ubuntu2004/serial"]
    extends: [".deb",".ubuntu2004"]