.ubuntu2604:
    image: ${REGISTRY}/build:ubuntu2604
build/ubuntu2604:
    extends: [".build",".ubuntu2604"]
    parallel:
        matrix:
            - BUILD_TYPE: [serial, openmp, mpi, hybrid]
test/ubuntu2604:
    extends: [".test",".ubuntu2604"]
    parallel:
        matrix:
            - {BUILD_TYPE: serial, RUN_TYPE: serial, RUNNER: small}
            - {BUILD_TYPE: openmp, RUN_TYPE: [serial, openmp], RUNNER: small}
            - {BUILD_TYPE: mpi, RUN_TYPE: [serial, mpi], RUNNER: small}
            - {BUILD_TYPE: hybrid, RUN_TYPE: [serial, openmp, mpi], RUNNER: small}
            - {BUILD_TYPE: hybrid, RUN_TYPE: hybrid, RUNNER: medium}
    needs:
        - job: build/ubuntu2604
          parallel:
              matrix:
                  - BUILD_TYPE: ['$[[ matrix.BUILD_TYPE ]]']
    tags: ["saas-linux-${RUNNER}-amd64"]

deb/ubuntu2604:
    extends: [".deb",".ubuntu2604"]
    variables: {DISTRO: ubuntu2604}
    parallel:
        matrix:
            - BUILD_TYPE: [serial, openmp, mpi, hybrid]
    needs:
        - job: build/ubuntu2604
          parallel:
              matrix:
                  - BUILD_TYPE: ['$[[ matrix.BUILD_TYPE ]]']
