! external functions implemented in fstr_ctr_util.c

external fstr_ctrl_get_err_msg

external fstr_ctrl_dump

external fstr_ctrl_open
external fstr_ctrl_get_rec_number
external fstr_ctrl_get_line
external fstr_ctrl_seek_header
external fstr_ctrl_seek_next_header
external fstr_ctrl_get_c_h_name
external fstr_ctrl_get_c_h_line_no
external fstr_ctrl_get_c_h_pos
external fstr_ctrl_get_param
external fstr_ctrl_get_param_ex
external fstr_ctrl_get_data_line_n
! external fstr_ctrl_copy_data_line
external fstr_ctrl_get_data_n_in_line
external fstr_ctrl_get_data_error_pos
external fstr_ctrl_get_data_error_line
external fstr_ctrl_get_data
! external fstr_ctrl_get_data_v
external fstr_ctrl_get_data_ex
! external fstr_ctrl_get_data_array
! external fstr_ctrl_get_data_array_v
external fstr_ctrl_get_data_array_ex
external fstr_ctrl_close
external fstr_ctrl_rewind

integer(kind=kint) :: fstr_ctrl_open
integer(kind=kint) :: fstr_ctrl_get_rec_number
integer(kind=kint) :: fstr_ctrl_get_line
integer(kind=kint) :: fstr_ctrl_seek_header
integer(kind=kint) :: fstr_ctrl_seek_next_header
integer(kind=kint) :: fstr_ctrl_get_c_h_name
integer(kind=kint) :: fstr_ctrl_get_c_h_line_no
integer(kind=kint) :: fstr_ctrl_get_c_h_pos
integer(kind=kint) :: fstr_ctrl_get_param
integer(kind=kint) :: fstr_ctrl_get_param_ex
integer(kind=kint) :: fstr_ctrl_get_data_line_n
! integer(kind=kint) :: fstr_ctrl_copy_data_line
integer(kind=kint) :: fstr_ctrl_get_data_n_in_line
integer(kind=kint) :: fstr_ctrl_get_data_error_pos
integer(kind=kint) :: fstr_ctrl_get_data_error_line
integer(kind=kint) :: fstr_ctrl_get_data
! integer(kind=kint) :: fstr_ctrl_get_data_v
integer(kind=kint) :: fstr_ctrl_get_data_ex
! integer(kind=kint) :: fstr_ctrl_get_data_array
! integer(kind=kint) :: fstr_ctrl_get_data_array_v
integer(kind=kint) :: fstr_ctrl_get_data_array_ex
integer(kind=kint) :: fstr_ctrl_close
integer(kind=kint) :: fstr_ctrl_rewind

private :: fstr_ctrl_get_err_msg
private :: fstr_ctrl_dump

private :: fstr_ctrl_open
private :: fstr_ctrl_get_rec_number
private :: fstr_ctrl_get_line
private :: fstr_ctrl_seek_header
private :: fstr_ctrl_seek_next_header
private :: fstr_ctrl_get_c_h_name
private :: fstr_ctrl_get_c_h_line_no
private :: fstr_ctrl_get_c_h_pos
private :: fstr_ctrl_get_param
private :: fstr_ctrl_get_param_ex
private :: fstr_ctrl_get_data_line_n
! private :: fstr_ctrl_copy_data_line
private :: fstr_ctrl_get_data_n_in_line
private :: fstr_ctrl_get_data_error_pos
private :: fstr_ctrl_get_data_error_line
private :: fstr_ctrl_get_data
! private :: fstr_ctrl_get_data_v
private :: fstr_ctrl_get_data_ex
! private :: fstr_ctrl_get_data_array
! private :: fstr_ctrl_get_data_array_v
private :: fstr_ctrl_get_data_array_ex
private :: fstr_ctrl_close
private :: fstr_ctrl_rewind




