
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer HECMW_hec_create_buffer
#define yy_delete_buffer HECMW_hec_delete_buffer
#define yy_scan_buffer HECMW_hec_scan_buffer
#define yy_scan_string HECMW_hec_scan_string
#define yy_scan_bytes HECMW_hec_scan_bytes
#define yy_init_buffer HECMW_hec_init_buffer
#define yy_flush_buffer HECMW_hec_flush_buffer
#define yy_load_buffer_state HECMW_hec_load_buffer_state
#define yy_switch_to_buffer HECMW_hec_switch_to_buffer
#define yypush_buffer_state HECMW_hecpush_buffer_state
#define yypop_buffer_state HECMW_hecpop_buffer_state
#define yyensure_buffer_stack HECMW_hecensure_buffer_stack
#define yy_flex_debug HECMW_hec_flex_debug
#define yyin HECMW_hecin
#define yyleng HECMW_hecleng
#define yylex HECMW_heclex
#define yylineno HECMW_heclineno
#define yyout HECMW_hecout
#define yyrestart HECMW_hecrestart
#define yytext HECMW_hectext
#define yywrap HECMW_hecwrap
#define yyalloc HECMW_hecalloc
#define yyrealloc HECMW_hecrealloc
#define yyfree HECMW_hecfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define HECMW_hec_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer HECMW_hec_create_buffer
#endif

#ifdef yy_delete_buffer
#define HECMW_hec_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer HECMW_hec_delete_buffer
#endif

#ifdef yy_scan_buffer
#define HECMW_hec_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer HECMW_hec_scan_buffer
#endif

#ifdef yy_scan_string
#define HECMW_hec_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string HECMW_hec_scan_string
#endif

#ifdef yy_scan_bytes
#define HECMW_hec_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes HECMW_hec_scan_bytes
#endif

#ifdef yy_init_buffer
#define HECMW_hec_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer HECMW_hec_init_buffer
#endif

#ifdef yy_flush_buffer
#define HECMW_hec_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer HECMW_hec_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define HECMW_hec_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state HECMW_hec_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define HECMW_hec_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer HECMW_hec_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define HECMW_hecpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state HECMW_hecpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define HECMW_hecpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state HECMW_hecpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define HECMW_hecensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack HECMW_hecensure_buffer_stack
#endif

#ifdef yylex
#define HECMW_heclex_ALREADY_DEFINED
#else
#define yylex HECMW_heclex
#endif

#ifdef yyrestart
#define HECMW_hecrestart_ALREADY_DEFINED
#else
#define yyrestart HECMW_hecrestart
#endif

#ifdef yylex_init
#define HECMW_heclex_init_ALREADY_DEFINED
#else
#define yylex_init HECMW_heclex_init
#endif

#ifdef yylex_init_extra
#define HECMW_heclex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra HECMW_heclex_init_extra
#endif

#ifdef yylex_destroy
#define HECMW_heclex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy HECMW_heclex_destroy
#endif

#ifdef yyget_debug
#define HECMW_hecget_debug_ALREADY_DEFINED
#else
#define yyget_debug HECMW_hecget_debug
#endif

#ifdef yyset_debug
#define HECMW_hecset_debug_ALREADY_DEFINED
#else
#define yyset_debug HECMW_hecset_debug
#endif

#ifdef yyget_extra
#define HECMW_hecget_extra_ALREADY_DEFINED
#else
#define yyget_extra HECMW_hecget_extra
#endif

#ifdef yyset_extra
#define HECMW_hecset_extra_ALREADY_DEFINED
#else
#define yyset_extra HECMW_hecset_extra
#endif

#ifdef yyget_in
#define HECMW_hecget_in_ALREADY_DEFINED
#else
#define yyget_in HECMW_hecget_in
#endif

#ifdef yyset_in
#define HECMW_hecset_in_ALREADY_DEFINED
#else
#define yyset_in HECMW_hecset_in
#endif

#ifdef yyget_out
#define HECMW_hecget_out_ALREADY_DEFINED
#else
#define yyget_out HECMW_hecget_out
#endif

#ifdef yyset_out
#define HECMW_hecset_out_ALREADY_DEFINED
#else
#define yyset_out HECMW_hecset_out
#endif

#ifdef yyget_leng
#define HECMW_hecget_leng_ALREADY_DEFINED
#else
#define yyget_leng HECMW_hecget_leng
#endif

#ifdef yyget_text
#define HECMW_hecget_text_ALREADY_DEFINED
#else
#define yyget_text HECMW_hecget_text
#endif

#ifdef yyget_lineno
#define HECMW_hecget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno HECMW_hecget_lineno
#endif

#ifdef yyset_lineno
#define HECMW_hecset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno HECMW_hecset_lineno
#endif

#ifdef yywrap
#define HECMW_hecwrap_ALREADY_DEFINED
#else
#define yywrap HECMW_hecwrap
#endif

#ifdef yyalloc
#define HECMW_hecalloc_ALREADY_DEFINED
#else
#define yyalloc HECMW_hecalloc
#endif

#ifdef yyrealloc
#define HECMW_hecrealloc_ALREADY_DEFINED
#else
#define yyrealloc HECMW_hecrealloc
#endif

#ifdef yyfree
#define HECMW_hecfree_ALREADY_DEFINED
#else
#define yyfree HECMW_hecfree
#endif

#ifdef yytext
#define HECMW_hectext_ALREADY_DEFINED
#else
#define yytext HECMW_hectext
#endif

#ifdef yyleng
#define HECMW_hecleng_ALREADY_DEFINED
#else
#define yyleng HECMW_hecleng
#endif

#ifdef yyin
#define HECMW_hecin_ALREADY_DEFINED
#else
#define yyin HECMW_hecin
#endif

#ifdef yyout
#define HECMW_hecout_ALREADY_DEFINED
#else
#define yyout HECMW_hecout
#endif

#ifdef yy_flex_debug
#define HECMW_hec_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug HECMW_hec_flex_debug
#endif

#ifdef yylineno
#define HECMW_heclineno_ALREADY_DEFINED
#else
#define yylineno HECMW_heclineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 102
#define YY_END_OF_BUFFER 103
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[574] =
    {   0,
        0,    0,    0,    5,    0,    0,  103,  101,    8,    9,
      101,  101,  101,   94,  100,  100,  100,   97,   93,   99,
       99,   95,   99,   99,   99,   99,   99,   99,   99,   99,
       96,   99,   99,   99,   99,  101,  101,  102,    2,  102,
      102,    5,    5,    4,    5,    6,  101,    8,    9,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   97,  100,
      100,   97,   98,   98,   97,  100,   99,    0,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    7,    0,    2,    0,    5,
        4,    4,    4,    5,    1,    5,    6,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   98,   98,   97,    0,
       98,   98,    0,  100,   98,  100,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    4,    4,    4,

        0,    0,    0,    0,    0,    0,    0,   27,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   98,   98,   98,   99,   99,   59,   99,   99,
       62,   99,   99,   99,   99,   67,   99,   99,   70,   99,
       72,   99,   99,   99,   99,   78,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   88,   89,   99,    0,    0,
        0,    0,    0,    0,    0,   26,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    4,    0,    0,    0,    0,   21,    0,    0,
        0,    0,    0,    0,   36,    0,    0,    0,   44,    0,

       48,    0,    0,    0,   56,   99,   99,   99,   99,   99,
       64,   65,   99,   99,   99,   99,   99,   99,   99,   99,
       79,   80,    0,   99,   99,   99,   99,   85,   99,   99,
       99,   90,    0,    0,    0,    0,   20,    0,    0,    0,
        0,    0,    0,    0,   35,    0,    0,    0,   43,    0,
       47,    0,    0,    0,   55,    0,    4,    0,    0,    0,
       19,    0,    0,    0,    0,    0,    0,    0,   40,   42,
        0,    0,    0,    0,   57,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   76,   99,    0,   99,
       99,   99,   84,   99,   99,   99,   99,    0,    0,    0,

       18,    0,    0,    0,    0,    0,    0,    0,    0,   39,
       41,    0,    0,    0,    0,    0,    4,    0,    0,    0,
       23,    0,    0,    0,    0,    0,    0,    0,   46,    0,
       52,   54,   99,   99,   99,   99,   99,   99,   69,   71,
       99,   99,   99,   77,    0,   99,   82,   99,   86,   99,
       99,   99,    0,    0,    0,   22,    0,    0,    0,    0,
       30,    0,    0,    0,   45,    0,   51,   53,    3,    3,
        0,    0,    0,   25,    0,    0,   32,    0,    0,   50,
       58,   99,   99,   63,   99,   68,   99,   99,   75,    0,
       81,   99,   99,   99,   99,    0,    0,    0,   24,    0,

        0,   31,    0,    0,   49,    3,    3,    0,    0,    0,
        0,    0,   29,    0,    0,   38,   60,   99,   66,   74,
       73,   81,   83,   99,   91,   92,    0,    0,    0,    0,
        0,   28,    0,    0,   37,   11,    0,    0,   17,    0,
       61,   99,   10,    0,    0,   16,    0,    0,    0,    0,
       87,    0,    0,    0,    0,   15,    0,    0,   14,    0,
       13,    0,   12,    0,    0,    0,    0,    0,    0,    0,
       34,   33,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    1,    7,    1,    1,    1,    1,    1,
        1,    1,    8,    9,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,    1,    1,
       15,    1,    1,    1,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   25,   38,   39,
        1,   12,    1,    1,   40,    1,   25,   25,   25,   25,

       41,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[42] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    4,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3
    } ;

static const flex_int16_t yy_base[586] =
    {   0,
        0,   36,   41,   45,   50,   52, 1276, 1277,   55, 1277,
     1272,   45,   51, 1277,   55, 1259,    0,   63, 1277,   68,
       75,   79,   85,   89,   95,  101,  105,  112,  116,  122,
      136,  146,  174,  151,  131,  207,   67, 1277, 1277, 1265,
     1233,    0, 1249,   44,  149, 1277, 1229,  159, 1277, 1203,
     1199,  165,   47, 1208,  179,   72, 1200, 1203,  191,    0,
     1199,  196,  158,  169,  204,  164,  207,  231,  236,  242,
      248,  252,  256,  265,  269,  278,  283,  287,  293,  299,
      303,  313,  318,  323,  329,  333,  340,  350,  354,  358,
      362,  366,  372,  380,  151, 1181, 1172,  377, 1179,   86,

     1179,  389,  200, 1171,  202, 1277,  225, 1277, 1169,    0,
        0,  281, 1162,  315, 1277,  353, 1277, 1150, 1150, 1141,
      109, 1146, 1140, 1134, 1114,  113, 1124, 1108, 1109, 1110,
      194, 1111, 1107, 1092, 1088, 1087,  368,  399,  402,  340,
      401,  403, 1102, 1098, 1096, 1091,  386,  416,  420,  424,
      437,  441,  445,  452,  456,  461,  466,  472,  483,  476,
      487,  493,  500,  507,  512,  517,  521,  526,  535,  539,
      543,  550,  554,  558,  568,  575, 1071, 1069, 1064,  219,
     1066, 1067, 1063, 1043, 1060,  152, 1052, 1034, 1037, 1035,
      229, 1038, 1035, 1013, 1008, 1005, 1018,  421,  505, 1016,

      998,  145,  991,  989,  987,  987,  987, 1277,  989,  977,
      965,  967,  970,  954,  956,  949,  944,  949,  931,  933,
      923,  924,  507,  554,  936,  579,  585,  589,  593,  601,
      605,  609,  613,  619,  623,  628,  632,  637,  645,  649,
      654,  662,  666,  671,  675,  679,  683,  691,  701,  705,
      710,  714,  718,  729,  733,  737,  745,  749,  916,  244,
      909,  909,  902,  901,  906, 1277,  904,  897,  883,  873,
      876,  879,  867,  867,  860,  858,  865,  849,  850,  841,
      838,  846,  842,  831,  831,  830,  804, 1277,  806,  820,
      819,  800,  797,  804, 1277,  792,  780,  791, 1277,  780,

     1277,  787,  775,  788, 1277,  753,  760,  764,  768,  773,
      779,  787,  791,  795,  802,  809,  815,  819,  825,  833,
      838,  842,  770,  846,  852,  857,  862,  866,  870,  880,
      884,  890,  776,  776,  778,  750, 1277,  748,  761,  758,
      736,  748,  731,  738, 1277,  726,  716,  726, 1277,  715,
     1277,  722,  707,  717, 1277,  716,  713,  697,  709,  705,
     1277,  688,  686,   72,  687,  689,  691,  680, 1277, 1277,
      668,  667,  662,  661,  894,  899,  903,  907,  911,  918,
      924,  932,  936,  940,  944,  949,  956,  960,  660,  964,
      969,  975,  981,  986,  990,  997, 1001,  645,  657,  652,

     1277,  639,  639,  252,  638,  626,  635,  636,  623, 1277,
     1277,  615,  609,  606,  605,  596,  594,  583,  575,  574,
     1277,  572,  572,  582,  565,  572,  557,  565, 1277,  547,
     1277, 1277, 1008, 1015, 1019, 1024, 1028, 1036, 1040, 1044,
     1049, 1053, 1059, 1063,  546, 1069, 1076, 1080, 1084, 1088,
     1092, 1096,  536,  529,  524, 1277,  518,  514,  523,  505,
     1277,  510,  499,  506, 1277,  487, 1277, 1277,    0,    0,
      487,  478,  286, 1277,  476,  461, 1277,  117,  459, 1277,
     1102, 1106, 1117, 1121, 1125, 1129, 1136, 1140, 1144,  462,
     1148, 1153, 1157, 1161, 1165,  457,  450,  328, 1277,  445,

      434, 1277,  291,  434, 1277,    0,    0,  438,  414,  416,
      425,  407, 1277,  419,  404, 1277, 1172, 1176, 1182, 1186,
     1191, 1277, 1195, 1199, 1203, 1207,  409,  390,  390,  385,
      364, 1277,  372,  356, 1277, 1277,  355,  347, 1277,  335,
     1211, 1215, 1277,  322,  318, 1277,  310,  294,  291,  287,
     1222,  268,  268,  267,  236, 1277,  241,  217, 1277,  212,
     1277,  199, 1277,  169,  171,  135,  120,  110,   90,   70,
     1277, 1277, 1277, 1236, 1240,   85, 1242, 1246, 1250, 1254,
     1258,   43, 1262, 1266, 1270
    } ;

static const flex_int16_t yy_def[586] =
    {   0,
      573,    1,  574,  575,    1,    1,  573,  573,  573,  573,
      573,  573,  573,  573,  576,  576,  576,  576,  573,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  573,  578,  573,  573,  573,
      573,  579,  579,  580,  581,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  576,
      576,  576,  576,  576,  576,  576,  577,  582,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  578,  573,  573,  573,  573,  573,

      573,  573,  573,  573,  578,  573,  578,  573,  573,  579,
      580,  583,  580,  581,  573,  581,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      576,  576,  573,  576,  576,  576,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  583,  583,  580,

      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  580,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,

      573,  573,  573,  573,  573,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  573,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  580,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  573,  577,
      577,  577,  577,  577,  577,  577,  577,  573,  573,  573,

      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  580,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  573,  577,  577,  577,  577,  577,
      577,  577,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  584,  585,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  573,
      577,  577,  577,  577,  577,  573,  573,  573,  573,  573,

      573,  573,  573,  573,  573,  584,  585,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  577,  577,  577,  577,
      577,  573,  577,  577,  577,  577,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      577,  577,  573,  573,  573,  573,  573,  573,  573,  573,
      577,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,    0,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573
    } ;

static const flex_int16_t yy_nxt[1319] =
    {   0,
        8,    9,   10,   11,    9,   12,    8,   13,   14,   15,
       16,   17,   18,    8,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   25,   25,   29,   30,   25,   25,
       25,   31,   32,   33,   25,   34,   25,   25,   25,   35,
       25,   36,   37,   39,   40,  146,   41,   39,   43,  112,
       44,   45,   46,   47,   46,   47,   48,   36,   37,   48,
       50,   58,   51,   59,   52,   61,  113,   62,   53,  106,
      107,   54,   55,   64,  126,   65,  423,   56,   60,   60,
      127,   68,   66,   57,   69,   60,   60,   60,   68,   60,
       60,  133,   68,  134,   70,   60,   60,  572,   68,   60,

       60,  424,   68,   66,   72,   60,   60,   71,   68,  135,
       73,   60,   60,  186,   68,   60,   60,  571,   68,  187,
       74,  514,   60,   60,   75,   68,   60,   60,  204,   68,
      210,   78,   60,   60,  515,   68,  211,   79,  570,   76,
      205,   60,   60,   80,  573,   77,   60,   60,  569,   68,
       81,  115,  116,  106,  107,   82,   60,   60,  568,   68,
       48,   60,   60,   48,   68,   83,   94,   84,   85,  269,
      141,  143,  285,  144,   86,  270,  145,   66,  286,   87,
       88,  142,  120,   89,   60,   60,  121,   68,   66,   90,
      122,  123,  124,   91,  567,  125,  129,   92,   66,  130,

      131,  138,  566,  139,  106,  107,   64,  132,   65,   66,
      140,   93,   95,  216,   64,   66,   65,   60,   60,  193,
      573,  194,   96,   66,   97,  217,   98,  106,  107,   99,
      100,  140,  565,  101,  102,  564,   66,  195,  262,  103,
       60,   60,   60,   60,   66,  104,   60,   60,  275,  573,
      263,  147,   60,   60,  563,  573,  458,  149,   60,   60,
      276,  573,   60,   60,  562,  573,   60,   60,  148,  573,
       60,  334,  151,  561,  150,   60,   60,  335,  573,   60,
       60,  459,  573,  115,  199,  560,  154,  152,   60,   60,
      510,  573,  153,   60,   60,  533,  573,   60,   60,  559,

      573,  558,  157,   60,   60,  557,  573,  155,  534,   60,
       60,  156,  573,   60,   60,  511,  573,  115,  116,  159,
      158,  162,  556,   60,   60,  160,  573,  555,   60,   60,
      161,  573,  529,   60,   60,  164,  573,  554,  163,   60,
       60,  553,  573,   60,   60,  552,  573,  143,  166,  143,
       60,   60,  225,  573,  165,  115,  116,  530,  167,  168,
       60,   60,  550,  573,   60,   60,  169,  573,   60,   60,
      549,  573,   60,   60,  172,  573,   60,   60,  548,  573,
      223,  170,   60,   60,  547,  573,  171,  140,  173,  534,
       60,   60,  174,  573,  179,  546,   60,   60,  180,  573,

      545,  175,  181,  182,  183,  176,  189,  184,  140,  190,
      191,  224,  138,  141,  139,  142,  226,  192,  140,  530,
       66,  140,   66,  115,  199,  544,   60,   60,  543,  573,
       60,   60,  540,  573,   60,   60,  515,  573,  539,  140,
      538,   66,  140,   66,  227,  511,  228,   60,   60,  537,
      573,   60,   60,  229,  573,   60,   60,  536,  573,  535,
      230,  532,   60,   60,  232,  573,   60,   60,  531,  573,
      231,   60,   60,  528,  573,  527,   60,   60,  233,  573,
      235,  522,   60,   60,  516,  573,   60,   60,  513,  573,
      234,  237,  236,   60,   60,  238,  573,   60,   60,  512,

      573,  509,  239,   60,   60,  508,  573,  115,  199,  240,
       60,   60,  242,  573,  505,  243,  241,   60,   60,  223,
      573,  504,   60,   60,  503,  573,  140,   60,   60,  502,
      573,   60,   60,  501,  573,  244,   60,   60,  500,  573,
      245,  246,  247,  459,  248,   60,   60,  140,  573,   60,
       60,  499,  573,   60,   60,  249,  573,  498,  250,  251,
       60,   60,  497,  573,   60,   60,  224,  573,   60,   60,
      496,  573,  490,  140,  480,  253,  252,  256,   60,   60,
      479,  573,  478,  255,  254,   60,   60,  257,  573,   60,
       60,  477,  573,  476,  140,   60,   60,  475,  573,   60,

       60,  424,  573,   60,   60,  474,  573,  473,  472,  258,
      307,   60,   60,  306,  573,   60,   60,  471,  573,   60,
       60,  308,  573,   60,   60,  470,  573,  469,  309,   60,
       60,  468,  573,   60,   60,  467,  573,  466,   60,   60,
      310,  573,   60,   60,  465,  573,  464,   60,   60,  311,
      573,  463,  312,  462,  313,   60,   60,  461,  573,   60,
       60,  460,  573,  314,   60,   60,  457,  573,  456,  455,
      315,  317,   60,   60,  454,  573,   60,   60,  453,  573,
      316,   60,   60,  445,  573,   60,   60,  432,  573,   60,
       60,  431,  573,   60,   60,  430,  573,  429,  320,  318,

      319,   60,   60,  428,  573,  323,  427,  426,  321,  322,
      425,   60,   60,  422,  573,   60,   60,  421,  573,  326,
       60,   60,  420,  573,   60,   60,  419,  573,   60,   60,
      418,  573,  417,  327,  324,  416,  415,  328,  325,   60,
       60,  414,  573,   60,   60,  413,  573,   60,   60,  412,
      573,  411,  330,  410,  329,   60,   60,  409,  573,   60,
       60,  408,  573,   60,   60,  407,  573,  406,  332,  405,
       60,   60,  331,  573,   60,   60,  404,  573,   60,   60,
      403,  573,  402,   60,   60,  375,  573,  401,  379,   60,
       60,  378,  573,  400,  376,  399,  377,   60,   60,  398,

      573,   60,   60,  389,  573,   60,   60,  374,  573,  373,
      372,  380,   60,   60,  371,  573,  370,  369,  381,   60,
       60,  382,  573,  368,  383,   60,   60,  367,  573,   60,
       60,  366,  573,  365,  384,   60,   60,  364,  573,  363,
      362,  361,  386,   60,   60,  360,  573,  385,   60,   60,
      359,  573,   60,   60,  358,  573,   60,   60,  387,  573,
      357,  388,   60,   60,  356,  573,  355,   60,   60,  390,
      573,  391,   60,   60,  354,  573,   60,   60,  353,  573,
       60,   60,  352,  573,  351,  394,  350,  349,  393,  392,
       60,   60,  348,  573,   60,   60,  347,  573,  346,  396,

       60,   60,  345,  573,   60,   60,  344,  573,  343,   60,
       60,  395,  573,   60,   60,  342,  573,   60,   60,  341,
      573,   60,   60,  397,  573,  340,  434,  339,   60,   60,
      338,  573,  433,  437,   60,   60,  337,  573,  336,  438,
      435,  333,   60,   60,  436,  573,   60,   60,  225,  573,
       60,   60,  305,  573,   60,   60,  304,  573,  439,   60,
       60,  303,  573,  440,  302,  441,   60,   60,  301,  573,
       60,   60,  300,  573,   60,   60,  299,  573,  442,   60,
       60,  298,  573,  297,  443,   60,   60,  444,  573,  296,
      446,   60,   60,  295,  573,  447,   60,   60,  294,  573,

       60,   60,  293,  573,  292,  450,  291,   60,   60,  448,
      573,   60,   60,  290,  573,  289,  288,  449,   60,   60,
      287,  573,  451,  284,  452,   60,   60,  481,  573,   60,
       60,  283,  573,  282,   60,   60,  281,  573,   60,   60,
      280,  573,  483,  484,  279,  485,   60,   60,  482,  573,
       60,   60,  278,  573,   60,   60,  277,  573,  274,   60,
       60,  486,  573,   60,   60,  273,  573,  272,  487,   60,
       60,  271,  573,   60,   60,  268,  573,  267,  489,   60,
       60,  266,  573,  265,  488,  264,   60,   60,  491,  573,
       60,   60,  261,  573,   60,   60,  260,  573,   60,   60,

      259,  573,   60,   60,   68,  573,   60,   60,  145,  573,
      145,  492,   60,   60,  225,  573,   60,   60,  222,  573,
      221,  493,  495,  220,  219,  517,  494,   60,   60,  218,
      573,   60,   60,  215,  573,   60,   60,  214,  573,   60,
       60,  213,  573,  212,  519,  518,   60,   60,  209,  573,
       60,   60,  208,  573,   60,   60,  207,  573,   60,   60,
      521,  573,  520,   60,   60,  206,  573,   60,   60,  203,
      573,   60,   60,  523,  573,   60,   60,  202,  573,  201,
      525,  200,   60,   60,  526,  573,   60,   60,  197,  573,
      196,  524,   60,   60,  188,  573,   60,   60,  185,  573,

      178,   60,   60,  541,  573,   60,   60,  177,  573,   60,
       60,   63,  573,   60,   60,  137,  573,   60,   60,  136,
      573,   60,   60,  128,  573,   60,   60,  119,  573,  118,
      542,  117,   60,   60,  551,  573,   38,   38,   38,   38,
       42,   42,   42,   42,   67,   67,  105,  105,  105,  105,
      110,  108,  110,  110,  111,  109,  111,  111,  114,  114,
      114,  114,  198,  198,  198,  198,  506,  108,  506,  506,
      507,   63,  507,  507,   49,  573,    7,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,

      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573
    } ;

static const flex_int16_t yy_chk[1319] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    2,    3,    3,  582,    3,    4,    4,   44,
        4,    4,    5,    5,    6,    6,    9,    6,    6,    9,
       12,   13,   12,   13,   12,   15,   44,   15,   12,   37,
       37,   12,   12,   18,   53,   18,  364,   12,   20,   20,
       53,   20,   18,   12,   20,   21,   21,  576,   21,   22,
       22,   56,   22,   56,   21,   23,   23,  570,   23,   24,

       24,  364,   24,   18,   23,   25,   25,   22,   25,   56,
       24,   26,   26,  100,   26,   27,   27,  569,   27,  100,
       26,  478,   28,   28,   27,   28,   29,   29,  121,   29,
      126,   29,   30,   30,  478,   30,  126,   30,  568,   28,
      121,   35,   35,   30,   35,   28,   31,   31,  567,   31,
       30,   45,   45,   95,   95,   31,   32,   32,  566,   32,
       48,   34,   34,   48,   34,   32,   34,   32,   32,  186,
       63,   66,  202,   66,   32,  186,   66,   63,  202,   32,
       32,   64,   52,   32,   33,   33,   52,   33,   64,   33,
       52,   52,   52,   33,  565,   52,   55,   33,   63,   55,

       55,   59,  564,   59,  105,  105,   62,   55,   62,   64,
       59,   33,   36,  131,   65,   62,   65,   67,   67,  103,
       67,  103,   36,   65,   36,  131,   36,  107,  107,   36,
       36,   59,  562,   36,   36,  560,   62,  103,  180,   36,
       68,   68,   68,   68,   65,   36,   69,   69,  191,   69,
      180,   69,   70,   70,  558,   70,  404,   70,   71,   71,
      191,   71,   72,   72,  557,   72,   73,   73,   69,   73,
       68,  260,   72,  555,   71,   74,   74,  260,   74,   75,
       75,  404,   75,  112,  112,  554,   75,   73,   76,   76,
      473,   76,   74,   77,   77,  503,   77,   78,   78,  553,

       78,  552,   77,   79,   79,  550,   79,   76,  503,   80,
       80,   76,   80,   81,   81,  473,   81,  114,  114,   79,
       78,   81,  549,   82,   82,   79,   82,  548,   83,   83,
       80,   83,  498,   84,   84,   83,   84,  547,   82,   85,
       85,  545,   85,   86,   86,  544,   86,  140,   85,  140,
       87,   87,  140,   87,   84,  116,  116,  498,   86,   87,
       88,   88,  540,   88,   89,   89,   88,   89,   90,   90,
      538,   90,   91,   91,   90,   91,   92,   92,  537,   92,
      137,   88,   93,   93,  534,   93,   89,  137,   91,  533,
       94,   94,   92,   94,   98,  531,  147,  147,   98,  147,

      530,   93,   98,   98,   98,   94,  102,   98,  137,  102,
      102,  138,  139,  141,  139,  142,  147,  102,  138,  529,
      141,  139,  142,  198,  198,  528,  148,  148,  527,  148,
      149,  149,  515,  149,  150,  150,  514,  150,  512,  138,
      511,  141,  139,  142,  148,  510,  149,  151,  151,  509,
      151,  152,  152,  150,  152,  153,  153,  508,  153,  504,
      151,  501,  154,  154,  153,  154,  155,  155,  500,  155,
      152,  156,  156,  497,  156,  496,  157,  157,  154,  157,
      156,  490,  158,  158,  479,  158,  160,  160,  476,  160,
      155,  158,  157,  159,  159,  158,  159,  161,  161,  475,

      161,  472,  159,  162,  162,  471,  162,  199,  199,  160,
      163,  163,  162,  163,  466,  163,  161,  164,  164,  223,
      164,  464,  165,  165,  463,  165,  223,  166,  166,  462,
      166,  167,  167,  460,  167,  164,  168,  168,  459,  168,
      164,  165,  166,  458,  167,  169,  169,  223,  169,  170,
      170,  457,  170,  171,  171,  168,  171,  455,  169,  170,
      172,  172,  454,  172,  173,  173,  224,  173,  174,  174,
      453,  174,  445,  224,  430,  172,  171,  174,  175,  175,
      428,  175,  427,  173,  172,  176,  176,  175,  176,  226,
      226,  426,  226,  425,  224,  227,  227,  424,  227,  228,

      228,  423,  228,  229,  229,  422,  229,  420,  419,  176,
      227,  230,  230,  226,  230,  231,  231,  418,  231,  232,
      232,  229,  232,  233,  233,  417,  233,  416,  230,  234,
      234,  415,  234,  235,  235,  414,  235,  413,  236,  236,
      232,  236,  237,  237,  412,  237,  409,  238,  238,  233,
      238,  408,  234,  407,  235,  239,  239,  406,  239,  240,
      240,  405,  240,  237,  241,  241,  403,  241,  402,  400,
      238,  242,  242,  242,  399,  242,  243,  243,  398,  243,
      240,  244,  244,  389,  244,  245,  245,  374,  245,  246,
      246,  373,  246,  247,  247,  372,  247,  371,  245,  243,

      244,  248,  248,  368,  248,  249,  367,  366,  247,  248,
      365,  249,  249,  363,  249,  250,  250,  362,  250,  251,
      251,  251,  360,  251,  252,  252,  359,  252,  253,  253,
      358,  253,  357,  252,  249,  356,  354,  253,  250,  254,
      254,  353,  254,  255,  255,  352,  255,  256,  256,  350,
      256,  348,  255,  347,  254,  257,  257,  346,  257,  258,
      258,  344,  258,  306,  306,  343,  306,  342,  258,  341,
      307,  307,  256,  307,  308,  308,  340,  308,  309,  309,
      339,  309,  338,  310,  310,  306,  310,  336,  310,  311,
      311,  309,  311,  335,  307,  334,  308,  312,  312,  333,

      312,  313,  313,  323,  313,  314,  314,  304,  314,  303,
      302,  313,  315,  315,  300,  315,  298,  297,  314,  316,
      316,  315,  316,  296,  316,  317,  317,  294,  317,  318,
      318,  293,  318,  292,  317,  319,  319,  291,  319,  290,
      289,  287,  318,  320,  320,  286,  320,  317,  321,  321,
      285,  321,  322,  322,  284,  322,  324,  324,  319,  324,
      283,  320,  325,  325,  282,  325,  281,  326,  326,  324,
      326,  325,  327,  327,  280,  327,  328,  328,  279,  328,
      329,  329,  278,  329,  277,  329,  276,  275,  327,  326,
      330,  330,  274,  330,  331,  331,  273,  331,  272,  331,

      332,  332,  271,  332,  375,  375,  270,  375,  269,  376,
      376,  330,  376,  377,  377,  268,  377,  378,  378,  267,
      378,  379,  379,  332,  379,  265,  377,  264,  380,  380,
      263,  380,  376,  380,  381,  381,  262,  381,  261,  381,
      378,  259,  382,  382,  379,  382,  383,  383,  225,  383,
      384,  384,  222,  384,  385,  385,  221,  385,  382,  386,
      386,  220,  386,  383,  219,  384,  387,  387,  218,  387,
      388,  388,  217,  388,  390,  390,  216,  390,  385,  391,
      391,  215,  391,  214,  386,  392,  392,  388,  392,  213,
      390,  393,  393,  212,  393,  391,  394,  394,  211,  394,

      395,  395,  210,  395,  209,  395,  207,  396,  396,  392,
      396,  397,  397,  206,  397,  205,  204,  394,  433,  433,
      203,  433,  396,  201,  397,  434,  434,  433,  434,  435,
      435,  200,  435,  197,  436,  436,  196,  436,  437,  437,
      195,  437,  435,  436,  194,  437,  438,  438,  434,  438,
      439,  439,  193,  439,  440,  440,  192,  440,  190,  441,
      441,  438,  441,  442,  442,  189,  442,  188,  441,  443,
      443,  187,  443,  444,  444,  185,  444,  184,  443,  446,
      446,  183,  446,  182,  442,  181,  447,  447,  446,  447,
      448,  448,  179,  448,  449,  449,  178,  449,  450,  450,

      177,  450,  451,  451,  146,  451,  452,  452,  145,  452,
      144,  448,  481,  481,  143,  481,  482,  482,  136,  482,
      135,  450,  452,  134,  133,  482,  451,  483,  483,  132,
      483,  484,  484,  130,  484,  485,  485,  129,  485,  486,
      486,  128,  486,  127,  485,  483,  487,  487,  125,  487,
      488,  488,  124,  488,  489,  489,  123,  489,  491,  491,
      488,  491,  487,  492,  492,  122,  492,  493,  493,  120,
      493,  494,  494,  492,  494,  495,  495,  119,  495,  118,
      494,  113,  517,  517,  495,  517,  518,  518,  109,  518,
      104,  493,  519,  519,  101,  519,  520,  520,   99,  520,

       97,  521,  521,  518,  521,  523,  523,   96,  523,  524,
      524,   61,  524,  525,  525,   58,  525,  526,  526,   57,
      526,  541,  541,   54,  541,  542,  542,   51,  542,   50,
      524,   47,  551,  551,  542,  551,  574,  574,  574,  574,
      575,  575,  575,  575,  577,  577,  578,  578,  578,  578,
      579,   43,  579,  579,  580,   41,  580,  580,  581,  581,
      581,  581,  583,  583,  583,  583,  584,   40,  584,  584,
      585,   16,  585,  585,   11,    7,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,

      573,  573,  573,  573,  573,  573,  573,  573,  573,  573,
      573,  573,  573,  573,  573,  573,  573,  573
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../src/common/hecmw_heclex.l"
#line 2 "../src/common/hecmw_heclex.l"
#include <string.h>
#include <errno.h>
#include "hecmw_heclex.h"
#include "hecmw_util.h"

typedef union {
	double dval;
	char *str;
} YYSTYPE;

static YYSTYPE yylval;
static int lineno;
static int lineno_inc;
static int flag_including = 0;
static FILE *incfp;
static char include_filename[HECMW_FILENAME_LEN+1];
static YY_BUFFER_STATE prev_state;
static int flag_header;

static void set_flag_header(int flag);
#line 1201 "<stdout>"

#line 1203 "<stdout>"

#define INITIAL 0
#define HEADER 1
#define INCLUDE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 38 "../src/common/hecmw_heclex.l"


#line 1426 "<stdout>"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 574 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1277 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 40 "../src/common/hecmw_heclex.l"
{ lineno++; set_flag_header(0); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 41 "../src/common/hecmw_heclex.l"
{ lineno++; set_flag_header(0); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 42 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_HEADER : ' '; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 43 "../src/common/hecmw_heclex.l"
{
						HECMW_heclex_unput_token();
						set_flag_header(1);
						BEGIN INITIAL;
					}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 48 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_HEADER; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 50 "../src/common/hecmw_heclex.l"
{ lineno_inc++; set_flag_header(0); return HECMW_HECLEX_NL; }
	YY_BREAK
case YY_STATE_EOF(INCLUDE):
#line 51 "../src/common/hecmw_heclex.l"
{
						yy_delete_buffer(YY_CURRENT_BUFFER);
						yy_switch_to_buffer(prev_state);
						if(fclose(incfp)) {
							HECMW_set_error(HECMW_IO_E0006,
								"File: %s, %s", include_filename, strerror(errno));
						}
						flag_including = 0;
						BEGIN INITIAL;
					}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 62 "../src/common/hecmw_heclex.l"
{ lineno++; set_flag_header(0); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 63 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 64 "../src/common/hecmw_heclex.l"
{ lineno++; set_flag_header(0); return HECMW_HECLEX_NL; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 66 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_AMPLITUDE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 67 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_AMPLITUDE : ' '; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 68 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_CONNECTIVITY; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 69 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_CONNECTIVITY : ' '; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 70 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_CONTACT_PAIR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 71 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_CONTACT_PAIR : ' '; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 72 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_EMBED_PAIR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 73 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_EMBED_PAIR : ' '; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 74 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_ECOPY; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 75 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_ECOPY : ' '; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 76 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_EGEN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 77 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_EGEN : ' '; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 78 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_EGROUP; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 79 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_EGROUP : ' '; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 80 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_ELEMENT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 81 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_ELEMENT : ' '; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 82 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_END; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 83 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_END : ' '; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 84 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_EQUATION; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 85 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_EQUATION : ' '; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 86 "../src/common/hecmw_heclex.l"
{
				BEGIN HEADER;
				set_flag_header(1);
				return HECMW_HECLEX_H_HEADER;
			}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 91 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_INCLUDE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 92 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_INCLUDE : ' '; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 93 "../src/common/hecmw_heclex.l"
{
							set_flag_header(1);
							return HECMW_HECLEX_H_INITIAL;
						}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 97 "../src/common/hecmw_heclex.l"
{
							return flag_header ? HECMW_HECLEX_H_INITIAL : ' ';
						}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 100 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_ITEM; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 101 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_ITEM : ' '; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 102 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_MATERIAL; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 103 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_MATERIAL : ' '; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 104 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_NCOPY; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 105 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_NCOPY : ' '; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 106 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_NFILL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 107 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_NFILL : ' '; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 108 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_NGEN; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 109 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_NGEN : ' '; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 110 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_NGROUP; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 111 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_NGROUP : ' '; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 112 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_NODE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 113 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_NODE : ' '; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 114 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_SECTION; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 115 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_SECTION : ' '; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 116 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_SGROUP; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 117 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_SGROUP : ' '; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 118 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_SYSTEM; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 119 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_SYSTEM : ' '; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 120 "../src/common/hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_ZERO; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 121 "../src/common/hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_ZERO : ' '; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 124 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_ABAQUS; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 125 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_ABSOLUTE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 126 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_BEAM; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 127 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_COMPOSITE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 128 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_DEFINITION; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 129 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_EGRP; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 130 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_GENERATE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 131 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_HECMW; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 132 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_INPUT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 133 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_INTERFACE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 134 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_ITEM; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 135 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_MATERIAL; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 136 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_MATITEM; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 137 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_NAME; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 138 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_NASTRAN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 139 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_NGRP; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 140 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_NODE_SURF; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 141 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_NODE_ELEM; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 142 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_RELATIVE; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 143 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_SECOPT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 144 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_SECTION; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 145 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_SGRP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 146 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_SHELL; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 147 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_SOLID; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 148 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_STEP_TIME; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 149 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_SUBITEM; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 150 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_SURF_SURF; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 151 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_SYSTEM; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 152 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_TABLE; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 153 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_TABULAR; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 154 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_TEMPERATURE; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 155 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_TIME; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 156 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_TYPE; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 157 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_VALUE; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 158 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_TIMEVALUE; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 159 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_VALUETIME; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 161 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return '='; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 162 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return ','; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 163 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return 'C'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 164 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return 'R'; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 166 "../src/common/hecmw_heclex.l"
{
				yylval.dval = atof(yytext);
				set_flag_header(0);
				return HECMW_HECLEX_INT;
			}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 171 "../src/common/hecmw_heclex.l"
{
				yylval.dval = atof(yytext);
				set_flag_header(0);
				return HECMW_HECLEX_DOUBLE;
			}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 176 "../src/common/hecmw_heclex.l"
{
				yylval.str = yytext;
				set_flag_header(0);
				return HECMW_HECLEX_NAME;
			}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 181 "../src/common/hecmw_heclex.l"
{
				yylval.str = yytext;
				set_flag_header(0);
				return HECMW_HECLEX_FILENAME;
			}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 186 "../src/common/hecmw_heclex.l"
{ set_flag_header(0); return yytext[0]; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(HEADER):
#line 187 "../src/common/hecmw_heclex.l"
{ return 0; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 189 "../src/common/hecmw_heclex.l"
ECHO;
	YY_BREAK
#line 2046 "<stdout>"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 574 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 574 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 573);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 189 "../src/common/hecmw_heclex.l"


static void
set_flag_header(int flag)
{
	flag_header = flag ? 1 : 0;
}


int
HECMW_heclex_get_lineno(void)
{
	return flag_including ? lineno_inc : lineno;
}


double
HECMW_heclex_get_number(void)
{
	return yylval.dval;
}


char *
HECMW_heclex_get_text(void)
{
	return yytext;
}


int
HECMW_heclex_is_including(void)
{
	return flag_including ? 1 : 0;
}


int
HECMW_heclex_next_token(void)
{
	return yylex();
}


int
HECMW_heclex_next_token_skip(int skip_token)
{
	int token;
	while((token = yylex())) {
		if(token != skip_token) break;
	}
	return token;
}


int
HECMW_heclex_set_input(FILE *fp)
{
	static int first = 1;
	if(fp == NULL) return -1;
	if(first) {
		yyin = fp;
		first = 0;
	} else {
		yyrestart(fp);
	}
	lineno = 1;
	return 0;
}


int
HECMW_heclex_skip_line(void)
{
	int token;
	while((token = HECMW_heclex_next_token())) {
		if(token == HECMW_HECLEX_NL) break;
	}
	return token;
}


int
HECMW_heclex_switch_to_include(const char *filename)
{
	if(filename == NULL) return -1;
	if(flag_including) {
		HECMW_set_error(HECMW_IO_E0004, "File: %s, %s", filename);
		return -1;
	}
	if((incfp = fopen(filename, "r")) == NULL) {
		HECMW_set_error(HECMW_IO_E0005, "File: %s, %s", filename, strerror(errno));
		return -1;
	}
	strcpy(include_filename, filename);
	prev_state = YY_CURRENT_BUFFER;
	yy_switch_to_buffer(yy_create_buffer(incfp, YY_BUF_SIZE));
	lineno_inc = 1;
	flag_including = 1;
	BEGIN INCLUDE;
	return 0;
}


int
HECMW_heclex_unput_token(void)
{
	char *p = yytext;
	while(*p) {
		if(*p == '\n') {
			if(YYSTATE == INCLUDE) {
				lineno_inc--;
			} else {
				lineno--;
			}
		}
		p++;
	}
	yyless(0);
	return 0;
}


int
HECMW_hecwrap(void)
{
	return 1;
}



