#define yy_create_buffer HECMW_hec_create_buffer
#define yy_delete_buffer HECMW_hec_delete_buffer
#define yy_scan_buffer HECMW_hec_scan_buffer
#define yy_scan_string HECMW_hec_scan_string
#define yy_scan_bytes HECMW_hec_scan_bytes
#define yy_flex_debug HECMW_hec_flex_debug
#define yy_init_buffer HECMW_hec_init_buffer
#define yy_flush_buffer HECMW_hec_flush_buffer
#define yy_load_buffer_state HECMW_hec_load_buffer_state
#define yy_switch_to_buffer HECMW_hec_switch_to_buffer
#define yyin HECMW_hecin
#define yyleng HECMW_hecleng
#define yylex HECMW_heclex
#define yyout HECMW_hecout
#define yyrestart HECMW_hecrestart
#define yytext HECMW_hectext
#define yywrap HECMW_hecwrap

#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 31
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L
#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 97
#define YY_END_OF_BUFFER 98
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[535] =
    {   0,
        0,    0,    0,    5,    0,    0,   98,   96,    8,    9,
       96,   96,   96,   89,   95,   93,   95,   92,   88,   94,
       94,   90,   94,   94,   94,   94,   94,   94,   94,   94,
       91,   94,   94,   94,   94,   96,   96,   97,    2,   97,
       97,    5,    5,    4,    5,    6,   96,    8,    9,    0,
        0,    0,    0,    0,    0,    0,    0,   93,   92,   95,
       93,   92,   93,   95,   94,    0,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    7,    0,    2,    0,    5,    4,    4,
        4,    5,    1,    5,    6,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   93,    0,    0,   95,   93,   95,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    4,
        4,    4,    0,    0,    0,    0,    0,    0,   25,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   93,   94,   94,   57,   94,   94,   60,
       94,   94,   94,   94,   65,   94,   94,   68,   94,   70,
       94,   94,   94,   94,   75,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   85,   86,   94,    0,    0,    0,
        0,    0,    0,   24,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        4,    0,    0,    0,    0,   19,    0,    0,    0,    0,
        0,   34,    0,    0,    0,   42,    0,   46,    0,    0,
        0,   54,   94,   94,   94,   94,   94,   62,   63,   94,

       94,   94,   94,   94,   94,   94,   94,   76,   77,    0,
       94,   94,   94,   94,   82,   94,   94,   87,    0,    0,
        0,    0,   18,    0,    0,    0,    0,    0,    0,   33,
        0,    0,    0,   41,    0,   45,    0,    0,    0,   53,
        0,    4,    0,    0,    0,   17,    0,    0,    0,    0,
        0,    0,   38,   40,    0,    0,    0,    0,   55,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   73,
       94,    0,   94,   94,   94,   81,   94,   94,    0,    0,
        0,   16,    0,    0,    0,    0,    0,    0,    0,   37,
       39,    0,    0,    0,    0,    0,    4,    0,    0,    0,

       21,    0,    0,    0,    0,    0,   44,    0,   50,   52,
       94,   94,   94,   94,   94,   94,   67,   69,   94,   94,
       74,    0,   94,   79,   94,   83,   94,    0,    0,    0,
       20,    0,    0,   28,    0,    0,    0,   43,    0,   49,
       51,    3,    3,    0,    0,    0,   23,    0,   30,    0,
        0,   48,   56,   94,   94,   61,   94,   66,   94,   72,
        0,   78,   94,   94,    0,    0,    0,   22,    0,   29,
        0,    0,   47,    3,    3,    0,    0,    0,    0,   27,
        0,    0,   36,   58,   94,   64,   71,   78,   80,   94,
        0,    0,    0,    0,   26,    0,    0,   35,   11,    0,

        0,    0,   59,   94,   10,    0,    0,    0,    0,    0,
        0,   84,    0,    0,    0,    0,   15,    0,    0,   14,
        0,   13,    0,   12,    0,    0,    0,    0,    0,    0,
        0,   32,   31,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    1,    7,    1,    1,    1,    1,    1,
        1,    1,    8,    9,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,    1,    1,
       15,    1,    1,    1,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   25,   38,   39,
        1,   12,    1,    1,   40,    1,   25,   25,   25,   25,

       41,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[42] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    4,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3
    } ;

static yyconst flex_int16_t yy_base[547] =
    {   0,
        0,   36,   41,   45,   50,   52, 1178, 1179,   55, 1179,
     1174,   45,   51, 1179,   55,   54,    0,   64, 1179,   68,
       76,   80,   86,   90,   96,  102,  106,  113,  117,  123,
      137,  147,  175,  152,  132,  208,   67, 1179, 1179, 1173,
     1152,    0, 1169,   70,  150, 1179, 1165,   81, 1179, 1129,
     1123,  162,   71, 1119,  176,  118, 1114,  142,  108,    0,
      159,  119,  188,  165,  192,  199,  204,  211,  231,  238,
      242,  249,  253,  258,  264,  268,  279,  275,  284,  297,
      302,  307,  313,  317,  324,  334,  338,  342,  346,  350,
      356,  364,  230, 1106, 1102,  361, 1109,  108, 1109,  373,

      224, 1101,  296, 1179,  301, 1179, 1097,    0,    0,  337,
     1091,  377, 1179,  381, 1179, 1077, 1075, 1070,   83, 1071,
     1068, 1044,  147, 1055, 1035, 1036, 1038,   91, 1040, 1034,
     1018, 1015, 1012,  253,  324, 1027, 1023, 1019, 1014,  385,
      389,  393,  397,  401,  410,  417,  421,  427,  431,  438,
      443,  457,  447,  461,  468,  473,  481,  486,  491,  495,
      500,  509,  513,  517,  524,  528,  532,  542,  549,  992,
      990,  987,  187,  989,  988,  968,  980,  178,  974,  956,
      957,  958,  265,  960,  959,  941,  937,  933,  945,  443,
      544,  943,  919,  223,  907,  905,  899,  894, 1179,  903,

      886,  872,  877,  878,  861,  863,  857,  854,  859,  841,
      842,  833,  833,  847,  553,  557,  561,  565,  575,  579,
      584,  588,  593,  597,  601,  606,  610,  619,  623,  628,
      635,  639,  645,  650,  654,  658,  666,  676,  680,  685,
      689,  693,  704,  708,  712,  720,  724,  832,  335,  824,
      822,  818,  816, 1179,  823,  817,  808,  795,  801,  807,
      795,  794,  788,  785,  790,  772,  773,  764,  763,  772,
      770,  761,  764,  766,  740, 1179,  739,  750,  734,  728,
      735, 1179,  723,  713,  721, 1179,  708, 1179,  717,  702,
      713, 1179,  728,  734,  738,  742,  746,  753,  761,  765,

      769,  776,  783,  789,  793,  797,  801,  807,  812,  695,
      821,  826,  830,  837,  841,  845,  854,  858,  703,  705,
      705,  679, 1179,  677,  691,  674,  686,  667,  674, 1179,
      661,  651,  660, 1179,  648, 1179,  658,  644,  656, 1179,
      651,  647,  629,  642,  640, 1179,  624,  624,  624,  624,
      625,  612, 1179, 1179,  602,  599,  596,  596,  862,  866,
      870,  876,  881,  885,  891,  897,  902,  906,  911,  915,
      920,  595,  924,  928,  932,  938,  942,  946,  580,  592,
      588, 1179,  571,  569,  568,  553,  563,  565,  556, 1179,
     1179,  548,  545,  540,  539,  525,  523,  514,  511,  507,

     1179,  503,  503,  506,  496,  502, 1179,  485, 1179, 1179,
      952,  957,  964,  969,  981,  986,  973,  990,  994,  999,
     1003,  481, 1009, 1013, 1019, 1023, 1027,  469,  467,  465,
     1179,  462,  465, 1179,  470,  460,  467, 1179,  450, 1179,
     1179,    0,    0,  457,  450,  187, 1179,  442, 1179,  250,
      440, 1179, 1031, 1035, 1042, 1046, 1052, 1056, 1062, 1066,
      444, 1070, 1074, 1078,  441,  432,  296, 1179,  425, 1179,
      312,  418, 1179,    0,    0,  416,  398,  400,  410, 1179,
      405,  390, 1179, 1082, 1086, 1090, 1094, 1179, 1098, 1104,
      397,  378,  380,  390, 1179,  380,  364, 1179, 1179,  364,

      358,  346, 1108, 1112, 1179,  348,  341,  327,  313,  310,
      303, 1116,  281,  278,  264,  243, 1179,  224,  202, 1179,
      214, 1179,  196, 1179,  187,  153,  150,  131,  121,   61,
       53, 1179, 1179, 1179, 1136, 1140,   47, 1142, 1146, 1150,
     1154, 1158,   43, 1162, 1166, 1170
    } ;

static yyconst flex_int16_t yy_def[547] =
    {   0,
      534,    1,  535,  536,    1,    1,  534,  534,  534,  534,
      534,  534,  534,  534,  537,  537,  537,  537,  534,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  534,  539,  534,  534,  534,
      534,  540,  540,  541,  542,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  537,
      537,  537,  537,  537,  538,  543,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  539,  534,  534,  534,  534,  534,  534,  534,

      534,  534,  539,  534,  539,  534,  534,  540,  541,  544,
      541,  542,  534,  542,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  537,  537,  537,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  544,
      544,  541,  534,  534,  534,  534,  534,  534,  534,  534,

      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      541,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  538,  538,  538,  538,  538,  538,  538,  538,

      538,  538,  538,  538,  538,  538,  538,  538,  538,  534,
      538,  538,  538,  538,  538,  538,  538,  538,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  541,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  534,  538,  538,  538,  538,  538,  538,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  541,  534,  534,  534,

      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  534,  538,  538,  538,  538,  538,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  545,  546,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  538,  538,  538,  538,  538,  538,  538,  538,
      534,  538,  538,  538,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  545,  546,  534,  534,  534,  534,  534,
      534,  534,  534,  538,  538,  538,  538,  534,  538,  538,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,

      534,  534,  538,  538,  534,  534,  534,  534,  534,  534,
      534,  538,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,    0,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534
    } ;

static yyconst flex_int16_t yy_nxt[1221] =
    {   0,
        8,    9,   10,   11,    9,   12,    8,   13,   14,   15,
       16,   17,   18,    8,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   25,   25,   29,   30,   25,   25,
       25,   31,   32,   33,   25,   34,   25,   25,   25,   35,
       25,   36,   37,   39,   40,  139,   41,   39,   43,   60,
       44,   45,   46,   47,   46,   47,   48,   36,   37,   48,
       50,   58,   51,   59,   52,   61,   63,   62,   53,  104,
      105,   54,   55,   64,   61,  110,   62,   56,   60,   60,
      533,   66,   48,   57,   67,   48,   60,   60,  532,   66,
       60,   60,  111,   66,   64,   68,   60,   60,  123,   66,

       60,   60,  196,   66,  124,   70,   60,   60,   69,   66,
      207,   71,   60,   60,  197,   66,   60,   60,   58,   66,
       59,   72,  208,   60,   60,   73,   66,   60,   60,   61,
       66,   62,   76,   60,   60,  178,   66,  130,   77,  131,
       74,  179,   60,   60,   78,  534,   75,   60,   60,  531,
       66,   79,  113,  114,  134,  132,   80,   60,   60,  530,
       66,  135,   60,   60,  201,   66,   81,   92,   82,   83,
      202,   63,  136,  529,  137,   84,  528,  138,   64,  118,
       85,   86,  135,  119,   87,   60,   60,  120,   66,  121,
       88,  478,  122,  126,   89,  257,  127,  128,   90,   64,

       63,  258,   60,   60,  129,  534,  251,   64,   60,   60,
       60,   60,   91,   93,   60,   60,  479,  534,  252,  140,
      527,   60,   60,   94,  534,   95,  142,   96,   64,  526,
       97,   98,  104,  105,   99,  100,  141,  525,   60,  524,
      101,   60,   60,  185,  534,  186,  102,  523,   60,   60,
      273,  534,   60,   60,  481,  534,  274,  143,  144,   60,
       60,  187,  534,   60,   60,  134,  534,  482,   60,   60,
      147,  534,  135,  145,   60,   60,  146,  534,   60,   60,
      522,  534,  521,  150,  263,   60,   60,  148,  534,   60,
       60,  149,  534,  135,   60,   60,  264,  534,  104,  105,

      493,  151,  155,  104,  105,  152,  154,   60,   60,  520,
      534,  153,   60,   60,  519,  534,  496,   60,   60,  157,
      534,  518,  156,   60,   60,  494,  534,   60,   60,  497,
      534,  136,  159,  136,   60,   60,  214,  534,  158,  113,
      191,  517,  160,  161,   60,   60,  516,  534,   60,   60,
      162,  534,   60,   60,  515,  534,   60,   60,  165,  534,
       60,   60,  320,  534,  514,  163,   60,   60,  321,  534,
      164,  513,  166,  511,   60,   60,  167,  534,  172,  113,
      114,  510,  173,  113,  114,  168,  174,  509,  175,  169,
      181,  176,  508,  182,  183,   60,   60,  497,  534,   60,

       60,  184,  534,   60,   60,  507,  534,   60,   60,  494,
      534,   60,   60,  506,  534,  215,  505,  216,  502,  217,
       60,   60,  482,  534,  219,  501,  218,   60,   60,  479,
      534,   60,   60,  500,  534,  499,  221,   60,   60,  220,
      534,   60,   60,  498,  534,  113,  191,  222,   60,   60,
      224,  534,  495,   60,   60,  492,  534,   60,   60,  491,
      534,  223,  226,  488,  225,  483,  227,   60,   60,  480,
      534,   60,   60,  477,  534,  476,  228,  473,   60,   60,
      229,  534,  472,   60,   60,  471,  534,  231,  232,  470,
      230,   60,   60,  469,  534,  468,   60,   60,  467,  534,

      466,   60,   60,  465,  534,   60,   60,  461,  534,  233,
       60,   60,  452,  534,  234,  235,  236,  451,  237,   60,
       60,  450,  534,   60,   60,  449,  534,   60,   60,  238,
      534,  448,  239,  240,   60,   60,  447,  534,   60,   60,
      446,  534,   60,   60,  445,  534,  113,  191,  444,  242,
      241,  245,   60,   60,  443,  534,  442,  244,  243,   60,
       60,  246,  534,   60,   60,  441,  534,   60,   60,  440,
      534,   60,   60,  439,  534,   60,   60,  438,  534,  437,
      436,  435,  294,  247,  434,   60,   60,  293,  534,   60,
       60,  433,  534,  295,   60,   60,  432,  534,   60,   60,

      431,  534,  296,   60,   60,  430,  534,   60,   60,  429,
      534,   60,   60,  428,  534,  297,   60,   60,  422,  534,
       60,   60,  410,  534,  298,  409,  299,  408,  300,   60,
       60,  407,  534,   60,   60,  406,  534,  301,   60,   60,
      405,  534,  404,  302,  304,   60,   60,  403,  534,   60,
       60,  402,  534,  401,  303,   60,   60,  400,  534,  399,
       60,   60,  398,  534,   60,   60,  397,  534,   60,   60,
      396,  534,  305,  307,  306,  395,   60,   60,  394,  534,
      310,  393,  392,  308,  309,  391,   60,   60,  390,  534,
       60,   60,  389,  534,  313,   60,   60,  388,  534,   60,

       60,  387,  534,   60,   60,  386,  534,  385,  314,  311,
      384,  383,  315,  312,   60,   60,  382,  534,   60,   60,
      381,  534,   60,   60,  380,  534,  379,  317,  372,  316,
       60,   60,  358,  534,   60,   60,  357,  534,   60,   60,
      356,  534,  355,  318,   60,   60,  354,  534,   60,   60,
      353,  534,   60,   60,  352,  534,   60,   60,  351,  534,
      359,  363,  350,   60,   60,  362,  534,  349,  360,  348,
      361,   60,   60,  347,  534,   60,   60,  346,  534,   60,
       60,  345,  534,  344,  343,  364,   60,   60,  342,  534,
      341,  340,  365,   60,   60,  366,  534,  339,  367,   60,

       60,  338,  534,   60,   60,  337,  534,   60,   60,  336,
      534,   60,   60,  335,  534,  334,  369,   60,   60,  333,
      534,  368,   60,   60,  332,  534,  331,  330,  329,  371,
      370,   60,   60,  328,  534,  327,   60,   60,  326,  534,
       60,   60,  325,  534,  373,  374,  324,   60,   60,  323,
      534,   60,   60,  322,  534,   60,   60,  319,  534,  214,
      377,  292,  375,  376,   60,   60,  291,  534,   60,   60,
      290,  534,   60,   60,  289,  534,   60,   60,  288,  534,
       60,   60,  287,  534,  286,  378,   60,   60,  285,  534,
      284,   60,   60,  412,  534,   60,   60,  283,  534,  411,

      415,   60,   60,  282,  534,  281,  416,   60,   60,  413,
      534,  280,   60,   60,  414,  534,   60,   60,  279,  534,
      278,   60,   60,  417,  534,   60,   60,  277,  534,  418,
       60,   60,  276,  534,   60,   60,  275,  534,   60,   60,
      419,  534,   60,   60,  272,  534,  420,  421,   60,   60,
      423,  534,   60,   60,  424,  534,   60,   60,  271,  534,
      270,  427,   60,   60,  269,  534,  425,   60,   60,  268,
      534,  453,  267,  426,   60,   60,  266,  534,  265,   60,
       60,  262,  534,   60,   60,  261,  534,  455,  456,  260,
      454,   60,   60,  259,  534,  256,   60,   60,  457,  534,

       60,   60,  255,  534,   60,   60,  254,  534,  253,   60,
       60,  458,  534,   60,   60,  250,  534,  249,  460,   60,
       60,  248,  534,   60,   60,  459,  534,   66,  462,   60,
       60,  138,  534,   60,   60,  138,  534,   60,   60,  214,
      534,   60,   60,  213,  534,   60,   60,  212,  534,  211,
      463,  210,   60,   60,  484,  534,   60,   60,  209,  534,
      464,  206,   60,   60,  205,  534,   60,   60,  204,  534,
      485,  486,   60,   60,  203,  534,   60,   60,  200,  534,
       60,   60,  487,  534,   60,   60,  199,  534,   60,   60,
      198,  534,   60,   60,  489,  534,   60,   60,  195,  534,

       60,   60,  194,  534,   60,   60,  193,  534,   60,   60,
      192,  534,  490,  503,   60,   60,  189,  534,   60,   60,
      188,  534,   60,   60,  180,  534,   60,   60,  177,  534,
      171,  512,  170,  133,  125,  504,   38,   38,   38,   38,
       42,   42,   42,   42,   65,   65,  103,  103,  103,  103,
      108,  117,  108,  108,  109,  116,  109,  109,  112,  112,
      112,  112,  190,  190,  190,  190,  474,  115,  474,  474,
      475,  106,  475,  475,  107,  106,   49,  534,    7,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,

      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534
    } ;

static yyconst flex_int16_t yy_chk[1221] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    2,    3,    3,  543,    3,    4,    4,  537,
        4,    4,    5,    5,    6,    6,    9,    6,    6,    9,
       12,   13,   12,   13,   12,   15,   16,   15,   12,   37,
       37,   12,   12,   16,   18,   44,   18,   12,   20,   20,
      531,   20,   48,   12,   20,   48,   21,   21,  530,   21,
       22,   22,   44,   22,   16,   21,   23,   23,   53,   23,

       24,   24,  119,   24,   53,   23,   25,   25,   22,   25,
      128,   24,   26,   26,  119,   26,   27,   27,   59,   27,
       59,   26,  128,   28,   28,   27,   28,   29,   29,   62,
       29,   62,   29,   30,   30,   98,   30,   56,   30,   56,
       28,   98,   35,   35,   30,   35,   28,   31,   31,  529,
       31,   30,   45,   45,   58,   56,   31,   32,   32,  528,
       32,   58,   34,   34,  123,   34,   32,   34,   32,   32,
      123,   61,   64,  527,   64,   32,  526,   64,   61,   52,
       32,   32,   58,   52,   32,   33,   33,   52,   33,   52,
       33,  446,   52,   55,   33,  178,   55,   55,   33,   61,

       63,  178,   65,   65,   55,   65,  173,   63,   66,   66,
       66,   66,   33,   36,   67,   67,  446,   67,  173,   67,
      525,   68,   68,   36,   68,   36,   68,   36,   63,  523,
       36,   36,   93,   93,   36,   36,   67,  521,   66,  519,
       36,   69,   69,  101,   69,  101,   36,  518,   70,   70,
      194,   70,   71,   71,  450,   71,  194,   69,   70,   72,
       72,  101,   72,   73,   73,  134,   73,  450,   74,   74,
       73,   74,  134,   71,   75,   75,   72,   75,   76,   76,
      516,   76,  515,   75,  183,   78,   78,   74,   78,   77,
       77,   74,   77,  134,   79,   79,  183,   79,  103,  103,

      467,   76,   79,  105,  105,   77,   78,   80,   80,  514,
       80,   77,   81,   81,  513,   81,  471,   82,   82,   81,
       82,  511,   80,   83,   83,  467,   83,   84,   84,  471,
       84,  135,   83,  135,   85,   85,  135,   85,   82,  110,
      110,  510,   84,   85,   86,   86,  509,   86,   87,   87,
       86,   87,   88,   88,  508,   88,   89,   89,   88,   89,
       90,   90,  249,   90,  507,   86,   91,   91,  249,   91,
       87,  506,   89,  502,   92,   92,   90,   92,   96,  112,
      112,  501,   96,  114,  114,   91,   96,  500,   96,   92,
      100,   96,  497,  100,  100,  140,  140,  496,  140,  141,

      141,  100,  141,  142,  142,  494,  142,  143,  143,  493,
      143,  144,  144,  492,  144,  140,  491,  141,  482,  142,
      145,  145,  481,  145,  144,  479,  143,  146,  146,  478,
      146,  147,  147,  477,  147,  476,  146,  148,  148,  145,
      148,  149,  149,  472,  149,  190,  190,  147,  150,  150,
      149,  150,  469,  151,  151,  466,  151,  153,  153,  465,
      153,  148,  151,  461,  150,  451,  151,  152,  152,  448,
      152,  154,  154,  445,  154,  444,  152,  439,  155,  155,
      153,  155,  437,  156,  156,  436,  156,  155,  156,  435,
      154,  157,  157,  433,  157,  432,  158,  158,  430,  158,

      429,  159,  159,  428,  159,  160,  160,  422,  160,  157,
      161,  161,  408,  161,  157,  158,  159,  406,  160,  162,
      162,  405,  162,  163,  163,  404,  163,  164,  164,  161,
      164,  403,  162,  163,  165,  165,  402,  165,  166,  166,
      400,  166,  167,  167,  399,  167,  191,  191,  398,  165,
      164,  167,  168,  168,  397,  168,  396,  166,  165,  169,
      169,  168,  169,  215,  215,  395,  215,  216,  216,  394,
      216,  217,  217,  393,  217,  218,  218,  392,  218,  389,
      388,  387,  216,  169,  386,  219,  219,  215,  219,  220,
      220,  385,  220,  218,  221,  221,  384,  221,  222,  222,

      383,  222,  219,  223,  223,  381,  223,  224,  224,  380,
      224,  225,  225,  379,  225,  221,  226,  226,  372,  226,
      227,  227,  358,  227,  222,  357,  223,  356,  224,  228,
      228,  355,  228,  229,  229,  352,  229,  226,  230,  230,
      351,  230,  350,  227,  231,  231,  231,  349,  231,  232,
      232,  348,  232,  347,  229,  233,  233,  345,  233,  344,
      234,  234,  343,  234,  235,  235,  342,  235,  236,  236,
      341,  236,  232,  234,  233,  339,  237,  237,  338,  237,
      238,  337,  335,  236,  237,  333,  238,  238,  332,  238,
      239,  239,  331,  239,  240,  240,  240,  329,  240,  241,

      241,  328,  241,  242,  242,  327,  242,  326,  241,  238,
      325,  324,  242,  239,  243,  243,  322,  243,  244,  244,
      321,  244,  245,  245,  320,  245,  319,  244,  310,  243,
      246,  246,  291,  246,  247,  247,  290,  247,  293,  293,
      289,  293,  287,  247,  294,  294,  285,  294,  295,  295,
      284,  295,  296,  296,  283,  296,  297,  297,  281,  297,
      293,  297,  280,  298,  298,  296,  298,  279,  294,  278,
      295,  299,  299,  277,  299,  300,  300,  275,  300,  301,
      301,  274,  301,  273,  272,  300,  302,  302,  271,  302,
      270,  269,  301,  303,  303,  302,  303,  268,  303,  304,

      304,  267,  304,  305,  305,  266,  305,  306,  306,  265,
      306,  307,  307,  264,  307,  263,  305,  308,  308,  262,
      308,  304,  309,  309,  261,  309,  260,  259,  258,  307,
      306,  311,  311,  257,  311,  256,  312,  312,  255,  312,
      313,  313,  253,  313,  311,  312,  252,  314,  314,  251,
      314,  315,  315,  250,  315,  316,  316,  248,  316,  214,
      316,  213,  313,  314,  317,  317,  212,  317,  318,  318,
      211,  318,  359,  359,  210,  359,  360,  360,  209,  360,
      361,  361,  208,  361,  207,  317,  362,  362,  206,  362,
      205,  363,  363,  361,  363,  364,  364,  204,  364,  360,

      364,  365,  365,  203,  365,  202,  365,  366,  366,  362,
      366,  201,  367,  367,  363,  367,  368,  368,  200,  368,
      198,  369,  369,  366,  369,  370,  370,  197,  370,  367,
      371,  371,  196,  371,  373,  373,  195,  373,  374,  374,
      368,  374,  375,  375,  193,  375,  369,  371,  376,  376,
      373,  376,  377,  377,  374,  377,  378,  378,  192,  378,
      189,  378,  411,  411,  188,  411,  375,  412,  412,  187,
      412,  411,  186,  377,  413,  413,  185,  413,  184,  414,
      414,  182,  414,  417,  417,  181,  417,  413,  414,  180,
      412,  415,  415,  179,  415,  177,  416,  416,  415,  416,

      418,  418,  176,  418,  419,  419,  175,  419,  174,  420,
      420,  416,  420,  421,  421,  172,  421,  171,  420,  423,
      423,  170,  423,  424,  424,  419,  424,  139,  423,  425,
      425,  138,  425,  426,  426,  137,  426,  427,  427,  136,
      427,  453,  453,  133,  453,  454,  454,  132,  454,  131,
      425,  130,  455,  455,  454,  455,  456,  456,  129,  456,
      427,  127,  457,  457,  126,  457,  458,  458,  125,  458,
      455,  457,  459,  459,  124,  459,  460,  460,  122,  460,
      462,  462,  459,  462,  463,  463,  121,  463,  464,  464,
      120,  464,  484,  484,  463,  484,  485,  485,  118,  485,

      486,  486,  117,  486,  487,  487,  116,  487,  489,  489,
      111,  489,  464,  485,  490,  490,  107,  490,  503,  503,
      102,  503,  504,  504,   99,  504,  512,  512,   97,  512,
       95,  504,   94,   57,   54,  490,  535,  535,  535,  535,
      536,  536,  536,  536,  538,  538,  539,  539,  539,  539,
      540,   51,  540,  540,  541,   50,  541,  541,  542,  542,
      542,  542,  544,  544,  544,  544,  545,   47,  545,  545,
      546,   43,  546,  546,   41,   40,   11,    7,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,

      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "hecmw_heclex.l"
#line 2 "hecmw_heclex.l"
#include <string.h>
#include <errno.h>
#include "hecmw_heclex.h"
#include "hecmw_util.h"

typedef union {
	double dval;
	char *str;
} YYSTYPE;

static YYSTYPE yylval;
static int lineno;
static int lineno_inc;
static int flag_including = 0;
static FILE *incfp;
static char include_filename[HECMW_FILENAME_LEN+1];
static YY_BUFFER_STATE prev_state;
static int flag_header;

static void set_flag_header(int flag);


#line 911 "<stdout>"

#define INITIAL 0
#define HEADER 1
#define INCLUDE 2

/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 38 "hecmw_heclex.l"


#line 1066 "<stdout>"

	if ( (yy_init) )
		{
		(yy_init) = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 535 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1179 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 40 "hecmw_heclex.l"
{ lineno++; set_flag_header(0); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 41 "hecmw_heclex.l"
{ lineno++; set_flag_header(0); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 42 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_HEADER : ' '; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 43 "hecmw_heclex.l"
{
						HECMW_heclex_unput_token();
						set_flag_header(1);
						BEGIN INITIAL;
					}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 48 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_HEADER; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 50 "hecmw_heclex.l"
{ lineno_inc++; set_flag_header(0); return HECMW_HECLEX_NL; }
	YY_BREAK
case YY_STATE_EOF(INCLUDE):
#line 51 "hecmw_heclex.l"
{
						yy_delete_buffer(YY_CURRENT_BUFFER);
						yy_switch_to_buffer(prev_state);
						if(fclose(incfp)) {
							HECMW_set_error(HECMW_IO_E0006,
								"File: %s, %s", include_filename, strerror(errno));
						}
						flag_including = 0;
						BEGIN INITIAL;
					}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 62 "hecmw_heclex.l"
{ lineno++; set_flag_header(0); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 63 "hecmw_heclex.l"
{ set_flag_header(0); }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 64 "hecmw_heclex.l"
{ lineno++; set_flag_header(0); return HECMW_HECLEX_NL; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 66 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_AMPLITUDE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 67 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_AMPLITUDE : ' '; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 68 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_CONNECTIVITY; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 69 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_CONNECTIVITY : ' '; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 70 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_CONTACT_PAIR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 71 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_CONTACT_PAIR : ' '; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 72 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_ECOPY; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 73 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_ECOPY : ' '; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 74 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_EGEN; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 75 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_EGEN : ' '; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 76 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_EGROUP; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 77 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_EGROUP : ' '; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 78 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_ELEMENT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 79 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_ELEMENT : ' '; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 80 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_END; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 81 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_END : ' '; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 82 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_EQUATION; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 83 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_EQUATION : ' '; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 84 "hecmw_heclex.l"
{
				BEGIN HEADER; 
				set_flag_header(1);
				return HECMW_HECLEX_H_HEADER;
			}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 89 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_INCLUDE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 90 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_INCLUDE : ' '; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 91 "hecmw_heclex.l"
{
							set_flag_header(1);
							return HECMW_HECLEX_H_INITIAL;
						}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 95 "hecmw_heclex.l"
{
							return flag_header ? HECMW_HECLEX_H_INITIAL : ' ';
						}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 98 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_ITEM; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 99 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_ITEM : ' '; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 100 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_MATERIAL; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 101 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_MATERIAL : ' '; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 102 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_NCOPY; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 103 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_NCOPY : ' '; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 104 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_NFILL; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 105 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_NFILL : ' '; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 106 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_NGEN; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 107 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_NGEN : ' '; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 108 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_NGROUP; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 109 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_NGROUP : ' '; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 110 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_NODE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 111 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_NODE : ' '; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 112 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_SECTION; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 113 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_SECTION : ' '; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 114 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_SGROUP; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 115 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_SGROUP : ' '; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 116 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_SYSTEM; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 117 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_SYSTEM : ' '; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 118 "hecmw_heclex.l"
{ set_flag_header(1); return HECMW_HECLEX_H_ZERO; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 119 "hecmw_heclex.l"
{ return flag_header ? HECMW_HECLEX_H_ZERO : ' '; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 122 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_ABAQUS; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 123 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_ABSOLUTE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 124 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_BEAM; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 125 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_COMPOSITE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 126 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_DEFINITION; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 127 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_EGRP; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 128 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_GENERATE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 129 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_HECMW; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 130 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_INPUT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 131 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_INTERFACE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 132 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_ITEM; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 133 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_MATERIAL; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 134 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_MATITEM; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 135 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_NAME; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 136 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_NASTRAN; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 137 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_NGRP; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 138 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_NODE_SURF; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 139 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_RELATIVE; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 140 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_SECOPT; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 141 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_SECTION; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 142 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_SGRP; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 143 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_SHELL; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 144 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_SOLID; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 145 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_STEP_TIME; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 146 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_SUBITEM; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 147 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_SURF_SURF; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 148 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_SYSTEM; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 149 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_TABLE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 150 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_TABULAR; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 151 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_TEMPERATURE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 152 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_TIME; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 153 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_TYPE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 154 "hecmw_heclex.l"
{ set_flag_header(0); return HECMW_HECLEX_K_VALUE; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 156 "hecmw_heclex.l"
{ set_flag_header(0); return '='; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 157 "hecmw_heclex.l"
{ set_flag_header(0); return ','; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 158 "hecmw_heclex.l"
{ set_flag_header(0); return 'C'; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 159 "hecmw_heclex.l"
{ set_flag_header(0); return 'R'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 161 "hecmw_heclex.l"
{
				yylval.dval = atof(yytext);
				set_flag_header(0);
				return HECMW_HECLEX_INT;
			}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 166 "hecmw_heclex.l"
{
				yylval.dval = atof(yytext);
				set_flag_header(0);
				return HECMW_HECLEX_DOUBLE;
			}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 171 "hecmw_heclex.l"
{
				yylval.str = yytext;
				set_flag_header(0);
				return HECMW_HECLEX_NAME;
			}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 176 "hecmw_heclex.l"
{
				yylval.str = yytext;
				set_flag_header(0);
				return HECMW_HECLEX_FILENAME;
			}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 181 "hecmw_heclex.l"
{ set_flag_header(0); return yytext[0]; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(HEADER):
#line 182 "hecmw_heclex.l"
{ return 0; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 184 "hecmw_heclex.l"
ECHO;
	YY_BREAK
#line 1687 "<stdout>"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 535 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 535 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 534);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * str )
{
    
	return yy_scan_bytes(str,strlen(str) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * bytes, int  len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
    	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
    	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 184 "hecmw_heclex.l"



static void
set_flag_header(int flag)
{
	flag_header = flag ? 1 : 0;
}


int
HECMW_heclex_get_lineno(void)
{
	return flag_including ? lineno_inc : lineno;
}


double
HECMW_heclex_get_number(void)
{
	return yylval.dval;
}


char *
HECMW_heclex_get_text(void)
{
	return yytext;
}


int
HECMW_heclex_is_including(void)
{
	return flag_including ? 1 : 0;
}


int
HECMW_heclex_next_token(void)
{
	return yylex();
}


int
HECMW_heclex_next_token_skip(int skip_token)
{
	int token;
	while((token = yylex())) {
		if(token != skip_token) break;
	}
	return token;
}


int
HECMW_heclex_set_input(FILE *fp)
{
	static int first = 1;	
	if(fp == NULL) return -1;
	if(first) {
		yyin = fp;
		first = 0;
	} else {
		yyrestart(fp);
	}
	lineno = 1;
	return 0;
}


int
HECMW_heclex_skip_line(void)
{
	int token;
	while((token = HECMW_heclex_next_token())) {
		if(token == HECMW_HECLEX_NL) break;
	}
	return token;
}


int
HECMW_heclex_switch_to_include(const char *filename)
{
	if(filename == NULL) return -1;
	if(flag_including) {
		HECMW_set_error(HECMW_IO_E0004, "File: %s, %s", filename);
		return -1;
	}
	if((incfp = fopen(filename, "r")) == NULL) {
		HECMW_set_error(HECMW_IO_E0005, "File: %s, %s", filename, strerror(errno));
		return -1;
	}
	strcpy(include_filename, filename);
	prev_state = YY_CURRENT_BUFFER;
	yy_switch_to_buffer(yy_create_buffer(incfp,YY_BUF_SIZE));
	lineno_inc = 1;
	flag_including = 1;
	BEGIN INCLUDE;
	return 0;
}


int
HECMW_heclex_unput_token(void)
{
	char *p = yytext;
	while(*p) {
		if(*p == '\n') {
			if(YYSTATE == INCLUDE) {
				lineno_inc--;
			} else {
				lineno--;
			}
		}
		p++;
	}
	yyless(0);
	return 0;
}


int
HECMW_hecwrap(void)
{
	return 1;
}



