#define yy_create_buffer HECMW_ctrl_create_buffer
#define yy_delete_buffer HECMW_ctrl_delete_buffer
#define yy_scan_buffer HECMW_ctrl_scan_buffer
#define yy_scan_string HECMW_ctrl_scan_string
#define yy_scan_bytes HECMW_ctrl_scan_bytes
#define yy_flex_debug HECMW_ctrl_flex_debug
#define yy_init_buffer HECMW_ctrl_init_buffer
#define yy_flush_buffer HECMW_ctrl_flush_buffer
#define yy_load_buffer_state HECMW_ctrl_load_buffer_state
#define yy_switch_to_buffer HECMW_ctrl_switch_to_buffer
#define yyin HECMW_ctrlin
#define yyleng HECMW_ctrlleng
#define yylex HECMW_ctrllex
#define yyout HECMW_ctrlout
#define yyrestart HECMW_ctrlrestart
#define yytext HECMW_ctrltext
#define yywrap HECMW_ctrlwrap

/* A lexical scanner generated by flex*/

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* Some routines like yy_flex_realloc() are emitted as static but are
   not called by all lexers. This generates warnings in some compilers,
   notably GCC. Arrange to suppress these. */
#ifdef __GNUC__
#define YY_MAY_BE_UNUSED __attribute__((unused))
#else
#define YY_MAY_BE_UNUSED
#endif

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t )) YY_MAY_BE_UNUSED;
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 40
#define YY_END_OF_BUFFER 41
static yyconst short int yy_accept[181] =
    {   0,
        0,    0,   41,   39,    2,    3,   39,   39,   39,   34,
       38,   36,   38,   35,   33,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   39,   39,
        2,    3,    0,    0,    0,    0,   36,   35,   38,   36,
       35,   36,   38,   37,    0,   37,   37,   37,   37,   37,
       22,   24,   37,   37,   37,   28,   37,   37,   37,    0,
        0,    0,    0,    0,    0,    1,    0,    0,    0,    0,
        0,   36,    0,    0,   38,   36,   38,   37,   17,   37,
       37,   37,   37,   37,   37,   37,   29,   30,   37,   37,
        0,    0,    0,    0,    0,    0,    0,    0,   36,   37,

       37,   37,   37,   37,   37,   26,   37,   37,   32,    0,
        0,    0,    0,    0,    7,    0,    0,    0,   37,   18,
       37,   37,   23,   25,   37,   37,    0,    6,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   16,   19,   37,
       37,   31,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   11,   15,   37,   37,   27,    0,    0,    0,   10,
       14,    5,    0,   13,   37,   37,    4,    0,   12,    0,
       37,   37,    0,    9,   20,   37,    8,   37,   21,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    1,    7,    1,    1,    1,    1,    1,
        1,    1,    8,    9,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,    1,    1,
       15,    1,    1,    1,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   25,   36,   25,   37,   25,
        1,   12,    1,    1,   38,    1,   25,   25,   25,   25,

       39,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       40,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[41] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        2,    2,    2,    3,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2
    } ;

static yyconst short int yy_base[185] =
    {   0,
        0,   35,  397,  486,   41,  486,  392,   26,   34,  486,
       37,   36,    0,   41,  486,   49,   53,   57,   62,   66,
       72,   79,   85,   90,   99,  103,  107,  114,  106,   84,
       93,  486,  362,  367,  365,  339,  109,   44,    0,  117,
       59,  122,  133,  138,  147,  151,  157,  161,  165,  169,
      179,  183,  187,  192,  199,  204,  210,  215,  219,  128,
      343,  347,  339,  322,  150,  486,  231,  324,  312,  310,
      324,  127,  199,  324,  320,  314,  309,  226,  231,  236,
      242,  247,  253,  257,  264,  268,  275,  279,  283,  289,
      293,  284,  280,  293,  270,  273,  238,  273,  272,  294,

      300,  304,  308,  314,  320,  324,  328,  335,  339,  249,
      254,  264,  251,  234,   57,  246,  234,  231,  344,  350,
      354,  359,  364,  368,  372,  378,  219,  195,  230,  215,
      215,  203,  206,  191,  170,  162,  160,  382,  388,  392,
      396,  402,  157,  162,  150,  146,  140,  138,  138,  126,
      117,  486,  486,  406,  411,  415,  119,  107,   82,  486,
      486,  486,   68,  486,  420,  424,  486,   65,  486,   64,
      429,  433,   59,  486,  437,  448,  486,  453,  457,  486,
       83,  479,  482,   49
    } ;

static yyconst short int yy_def[185] =
    {   0,
      180,    1,  180,  180,  180,  180,  180,  180,  180,  180,
      181,  181,  181,  181,  180,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  180,  183,
      180,  180,  180,  180,  180,  180,  180,  180,  181,  181,
      181,  181,  181,  182,  184,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  183,
      180,  180,  180,  180,  183,  180,  183,  180,  180,  180,
      180,  180,  180,  180,  181,  181,  181,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  182,

      182,  182,  182,  182,  182,  182,  182,  182,  182,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  182,  182,
      182,  182,  182,  182,  182,  182,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  182,  182,  182,
      182,  182,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  182,  182,  182,  180,  180,  180,  180,
      180,  180,  180,  180,  182,  182,  180,  180,  180,  180,
      182,  182,  180,  180,  182,  182,  180,  182,  182,    0,
      180,  180,  180,  180
    } ;

static yyconst short int yy_nxt[527] =
    {   0,
        4,    5,    6,    7,    5,    8,    4,    9,   10,   11,
       12,   13,   14,    4,   15,   16,   17,   17,   18,   17,
       19,   20,   21,   22,   17,   23,   17,   24,   25,   17,
       17,   26,   17,   27,   17,   17,   17,   28,   17,   17,
       29,   30,   31,   33,   37,   31,   38,   40,   42,   41,
       77,   40,   34,   41,   37,   43,   38,   35,   36,   39,
       39,  133,   45,   39,   39,   46,   45,   39,   39,   40,
       45,   41,   39,   39,   43,   45,   39,   39,  134,   45,
       47,   48,   39,   39,   39,   45,   66,   67,  177,   39,
       39,   50,   45,  174,   31,   39,   39,   31,   45,  173,

       39,   39,  170,   45,   49,   54,   51,   52,   53,   39,
       39,   60,   45,   39,   39,  169,   45,   39,   39,   55,
       45,   72,   58,   61,   39,   39,   56,  180,   73,   42,
       66,   67,   62,   57,   42,  168,   43,   63,   64,   72,
       74,   43,   75,   59,  167,   76,   73,   73,   39,   39,
      164,  180,   66,   67,  163,   43,   39,   39,   39,   39,
       43,   39,   39,  162,  180,   73,   78,   39,   39,  161,
      180,   39,   39,  160,  180,   39,   39,  159,  180,   39,
       39,  158,  180,  145,   39,  157,   82,   80,   79,   39,
       39,  153,  180,   39,   39,  152,  180,   39,   39,  144,

      180,  151,   39,   39,   81,  180,   74,   83,   74,   39,
       39,   99,  180,   84,   39,   39,  145,  180,   85,   87,
       39,   39,  150,  180,   86,   39,   39,  134,  180,   39,
       39,  149,  180,   66,   67,   89,   39,   39,  148,  180,
      147,   39,   39,   88,  180,  146,   39,   39,   90,  180,
      143,  101,   39,   39,  137,  180,  100,   39,   39,  136,
      180,  135,  102,   39,   39,  132,  180,   39,   39,  131,
      180,  116,  117,  103,   39,   39,  128,  180,   39,   39,
      105,  180,  127,  106,   99,   39,   39,  104,  180,   39,
       39,  118,  180,   39,   39,  115,  180,  129,  130,   39,

       39,  107,  180,  114,   39,   39,  108,  180,  109,  113,
       39,   39,  112,  180,   39,   39,  111,  180,   39,   39,
      110,  180,   45,  121,   39,   39,   76,  180,  119,  120,
       39,   39,   76,  180,   39,   39,   99,  180,   39,   39,
       98,  180,   97,  122,   96,   39,   39,  123,  180,   39,
       39,   95,  180,  124,   39,   39,   94,  180,   93,  125,
       39,   39,  126,  180,   39,   39,   92,  180,  140,   39,
       39,   91,  180,   71,   39,   39,  138,  180,   39,   39,
      139,  180,   39,   39,   70,  180,   69,  141,   39,   39,
       68,  180,   39,   39,   32,  180,  180,  142,   39,   39,

      180,  180,   39,   39,  180,  180,   39,   39,  180,  180,
      154,  155,   39,   39,  180,  180,   39,   39,  180,  180,
      180,   39,   39,  156,  180,   39,   39,  180,  180,  165,
       39,   39,  180,  180,   39,   39,  180,  180,  166,   39,
       39,  180,  180,   39,   39,  180,  180,   39,   39,  180,
      180,  180,  171,  180,  180,  180,  176,  172,   39,   39,
      180,  180,  175,   39,   39,  180,  180,   39,   39,  180,
      180,  180,  179,  180,  180,  180,  180,  180,  180,  178,
       44,   44,   65,   65,   65,    3,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,

      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180
    } ;

static yyconst short int yy_chk[527] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    2,    5,    8,    9,    5,    9,   11,   12,   11,
      184,   14,    8,   14,   38,   12,   38,    8,    8,   16,
       16,  115,   16,   17,   17,   16,   17,   18,   18,   41,
       18,   41,   19,   19,   12,   19,   20,   20,  115,   20,
       18,   19,   21,   21,  181,   21,   30,   30,  173,   22,
       22,   21,   22,  170,   31,   23,   23,   31,   23,  168,

       24,   24,  163,   24,   20,   24,   22,   22,   23,   25,
       25,   29,   25,   26,   26,  159,   26,   27,   27,   25,
       27,   37,   26,   29,   28,   28,   25,   28,   37,   40,
       60,   60,   29,   25,   42,  158,   40,   29,   29,   72,
       43,   42,   43,   27,  157,   43,   72,   37,   44,   44,
      151,   44,   65,   65,  150,   40,   45,   45,   45,   45,
       42,   46,   46,  149,   46,   72,   46,   47,   47,  148,
       47,   48,   48,  147,   48,   49,   49,  146,   49,   50,
       50,  145,   50,  144,   45,  143,   50,   48,   47,   51,
       51,  137,   51,   52,   52,  136,   52,   53,   53,  128,

       53,  135,   54,   54,   49,   54,   73,   51,   73,   55,
       55,   73,   55,   53,   56,   56,  128,   56,   54,   55,
       57,   57,  134,   57,   54,   58,   58,  133,   58,   59,
       59,  132,   59,   67,   67,   58,   78,   78,  131,   78,
      130,   79,   79,   57,   79,  129,   80,   80,   59,   80,
      127,   80,   81,   81,  118,   81,   78,   82,   82,  117,
       82,  116,   81,   83,   83,  114,   83,   84,   84,  113,
       84,   97,   97,   82,   85,   85,  111,   85,   86,   86,
       84,   86,  110,   85,   99,   87,   87,   83,   87,   88,
       88,   98,   88,   89,   89,   96,   89,  112,  112,   90,

       90,   86,   90,   95,  100,  100,   89,  100,   90,   94,
      101,  101,   93,  101,  102,  102,   92,  102,  103,  103,
       91,  103,   77,  102,  104,  104,   76,  104,  100,  101,
      105,  105,   75,  105,  106,  106,   74,  106,  107,  107,
       71,  107,   70,  103,   69,  108,  108,  104,  108,  109,
      109,   68,  109,  105,  119,  119,   64,  119,   63,  107,
      120,  120,  108,  120,  121,  121,   62,  121,  122,  122,
      122,   61,  122,   36,  123,  123,  119,  123,  124,  124,
      121,  124,  125,  125,   35,  125,   34,  125,  126,  126,
       33,  126,  138,  138,    7,  138,    3,  126,  139,  139,

        0,  139,  140,  140,    0,  140,  141,  141,    0,  141,
      140,  140,  142,  142,    0,  142,  154,  154,    0,  154,
        0,  155,  155,  141,  155,  156,  156,    0,  156,  154,
      165,  165,    0,  165,  166,  166,    0,  166,  155,  171,
      171,    0,  171,  172,  172,    0,  172,  175,  175,    0,
      175,    0,  165,    0,    0,    0,  172,  166,  176,  176,
        0,  176,  171,  178,  178,    0,  178,  179,  179,    0,
      179,    0,  178,    0,    0,    0,    0,    0,    0,  176,
      182,  182,  183,  183,  183,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,

      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../src/common/hecmw_ctrllex.l"
#define INITIAL 0
#line 2 "../src/common/hecmw_ctrllex.l"
#include <string.h>
#include <errno.h>
#include "hecmw_ctrllex.h"
#include "hecmw_util.h"

typedef union {
	double dval;
	char *str;
} YYSTYPE;

static YYSTYPE yylval;
static int lineno;
static int flag_header;

static void set_flag_header(int flag);
#define YY_NO_UNPUT 1

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 30 "../src/common/hecmw_ctrllex.l"



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 181 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 486 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 32 "../src/common/hecmw_ctrllex.l"
{ lineno++; set_flag_header(0); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 33 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 34 "../src/common/hecmw_ctrllex.l"
{ lineno++; set_flag_header(0); return HECMW_CTRLLEX_NL; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 36 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(1); return HECMW_CTRLLEX_H_CONTROL; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 37 "../src/common/hecmw_ctrllex.l"
{ return flag_header ? HECMW_CTRLLEX_H_CONTROL : ' '; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 38 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(1); return HECMW_CTRLLEX_H_MESH; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 39 "../src/common/hecmw_ctrllex.l"
{ return flag_header ? HECMW_CTRLLEX_H_MESH : ' '; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 40 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(1); return HECMW_CTRLLEX_H_MESH_GROUP; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 41 "../src/common/hecmw_ctrllex.l"
{ return flag_header ? HECMW_CTRLLEX_H_MESH_GROUP : ' '; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 42 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(1); return HECMW_CTRLLEX_H_RESULT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 43 "../src/common/hecmw_ctrllex.l"
{ return flag_header ? HECMW_CTRLLEX_H_RESULT : ' '; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 44 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(1); return HECMW_CTRLLEX_H_RESTART; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 45 "../src/common/hecmw_ctrllex.l"
{ return flag_header ? HECMW_CTRLLEX_H_RESTART : ' '; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 46 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(1); return HECMW_CTRLLEX_H_SUBDIR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 47 "../src/common/hecmw_ctrllex.l"
{ return flag_header ? HECMW_CTRLLEX_H_SUBDIR : ' '; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 49 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_ABAQUS; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 50 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_DIR; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 51 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_FEMAP; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 52 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_GEOFEM; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 53 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_HECMW_DIST; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 54 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_HECMW_ENTIRE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 55 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_IN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 56 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_INOUT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 57 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_IO; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 58 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_LIMIT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 59 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_NAME; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 60 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_NASTRAN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 61 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_ON; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 62 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_OFF; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 63 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_OUT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 64 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_REFINE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 65 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_TYPE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 68 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return '='; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 69 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return ','; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 71 "../src/common/hecmw_ctrllex.l"
{
				yylval.dval = atof(yytext);
				set_flag_header(0);
				return HECMW_CTRLLEX_INT;
			}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 76 "../src/common/hecmw_ctrllex.l"
{
				yylval.dval = atof(yytext);
				set_flag_header(0);
				return HECMW_CTRLLEX_DOUBLE;
			}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 81 "../src/common/hecmw_ctrllex.l"
{
				yylval.str = yytext;
				set_flag_header(0);
				return HECMW_CTRLLEX_NAME;
			}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 86 "../src/common/hecmw_ctrllex.l"
{
				yylval.str = yytext;
				set_flag_header(0);
				return HECMW_CTRLLEX_FILENAME;
			}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 91 "../src/common/hecmw_ctrllex.l"
{ set_flag_header(0); return yytext[0]; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 92 "../src/common/hecmw_ctrllex.l"
{ return 0; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 94 "../src/common/hecmw_ctrllex.l"
ECHO;
	YY_BREAK

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 181 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 181 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 180);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 94 "../src/common/hecmw_ctrllex.l"


static void
set_flag_header(int flag)
{
	flag_header = flag ? 1 : 0;
}


int
HECMW_ctrllex_get_lineno(void)
{
	return lineno;
}


double
HECMW_ctrllex_get_number(void)
{
	return yylval.dval;
}


char *
HECMW_ctrllex_get_text(void)
{
	return yytext;
}


int
HECMW_ctrllex_next_token(void)
{
	return yylex();
}


int
HECMW_ctrllex_next_token_skip(int skip_token)
{
	int token;
	while((token = yylex())) {
		if(token != skip_token) break;
	}
	return token;
}


int
HECMW_ctrllex_set_input(FILE *fp)
{
	static int first = 1;
	if(fp == NULL) return -1;
	if(first) {
		yyin = fp;
		first = 0;
	} else {
		yyrestart(fp);
	}
	lineno = 1;
	return 0;
}


int
HECMW_ctrllex_skip_line(void)
{
	int token;
	while((token = HECMW_ctrllex_next_token())) {
		if(token == HECMW_CTRLLEX_NL) break;
	}
	return token;
}


int
HECMW_ctrllex_unput_token(void)
{
	char *p = yytext;
	while(*p) {
		if(*p == '\n') {
			lineno--;
		}
		p++;
	}
	yyless(0);
	return 0;
}


int
HECMW_ctrlwrap(void)
{
	return 1;
}
