/*****************************************************************************
 * Copyright (c) 2019 FrontISTR Commons
 * This software is released under the MIT License, see LICENSE.txt
 *****************************************************************************/

#ifndef HECMW_INPLEX_INCLUDED
#define HECMW_INPLEX_INCLUDED

#include <stdio.h>

enum {
  HECMW_INPLEX_NL = 1000,
  HECMW_INPLEX_INT,
  HECMW_INPLEX_DOUBLE,
  HECMW_INPLEX_NAME,
  HECMW_INPLEX_FILENAME,
  HECMW_INPLEX_HEADER,

  HECMW_INPLEX_H_AMPLITUDE = 2000,
  HECMW_INPLEX_H_CONDUCTIVITY,
  HECMW_INPLEX_H_DENSITY,
  HECMW_INPLEX_H_ELASTIC,
  HECMW_INPLEX_H_ELEMENT,
  HECMW_INPLEX_H_ELSET,
  HECMW_INPLEX_H_EXPANSION,
  HECMW_INPLEX_H_EQUATION,
  HECMW_INPLEX_H_HEADING,
  HECMW_INPLEX_H_INCLUDE,
  HECMW_INPLEX_H_INITIAL,
  HECMW_INPLEX_H_MATERIAL,
  HECMW_INPLEX_H_NODE,
  HECMW_INPLEX_H_NSET,
  HECMW_INPLEX_H_SHELL_SECTION,
  HECMW_INPLEX_H_SOLID_SECTION,
  HECMW_INPLEX_H_SPECIFIC_HEAT,
  HECMW_INPLEX_H_SYSTEM,
  HECMW_INPLEX_H_BOUNDARY,
  HECMW_INPLEX_H_CLOAD,
  HECMW_INPLEX_H_DLOAD,
  HECMW_INPLEX_H_TIE,
  HECMW_INPLEX_H_TRS,
  HECMW_INPLEX_H_VISCOELASTIC,
  HECMW_INPLEX_H_NODE_OUTPUT,
  HECMW_INPLEX_H_ELEMENT_OUTPUT,

  HECMW_INPLEX_K_ABSOLUTE = 3000,
  HECMW_INPLEX_K_ANISOTROPIC,
  HECMW_INPLEX_K_ELSET,
  HECMW_INPLEX_K_ENGINEERING_CONSTANTS,
  HECMW_INPLEX_K_DEFINITION,
  HECMW_INPLEX_K_DEPENDENCIES,
  HECMW_INPLEX_K_GENERATE,
  HECMW_INPLEX_K_INPUT,
  HECMW_INPLEX_K_ISOTROPIC,
  HECMW_INPLEX_K_INSTANCE,
  HECMW_INPLEX_K_INSTANTANEOUS,
  HECMW_INPLEX_K_LAMINA,
  HECMW_INPLEX_K_MATERIAL,
  HECMW_INPLEX_K_MODULI,
  HECMW_INPLEX_K_NAME,
  HECMW_INPLEX_K_NSET,
  HECMW_INPLEX_K_ORTHOTROPIC,
  HECMW_INPLEX_K_ORIENTATION,
  HECMW_INPLEX_K_RELATIVE,
  HECMW_INPLEX_K_STEP_TIME,
  HECMW_INPLEX_K_SYSTEM,
  HECMW_INPLEX_K_TABULAR,
  HECMW_INPLEX_K_TEMPERATURE,
  HECMW_INPLEX_K_TIME,
  HECMW_INPLEX_K_TYPE,
  HECMW_INPLEX_K_UNSORTED,
  HECMW_INPLEX_K_VALUE,
  HECMW_INPLEX_K_ZERO,
  HECMW_INPLEX_K_PRONY,
  HECMW_INPLEX_K_TIMEVALUE,
  HECMW_INPLEX_K_VALUETIME,

  /* element type */
  HECMW_INPLEX_E_B31 = 4000,
  HECMW_INPLEX_E_B32,
  HECMW_INPLEX_E_C3D4,
  HECMW_INPLEX_E_C3D6,
  HECMW_INPLEX_E_C3D8,
  HECMW_INPLEX_E_C3D8I,
  HECMW_INPLEX_E_C3D10,
  HECMW_INPLEX_E_C3D15,
  HECMW_INPLEX_E_C3D20,
  HECMW_INPLEX_E_CAX3,
  HECMW_INPLEX_E_CAX4,
  HECMW_INPLEX_E_CAX4I,
  HECMW_INPLEX_E_CAX4R,
  HECMW_INPLEX_E_CAX6,
  HECMW_INPLEX_E_CAX8,
  HECMW_INPLEX_E_CAX8R,
  HECMW_INPLEX_E_CPE3,
  HECMW_INPLEX_E_CPE4,
  HECMW_INPLEX_E_CPE4I,
  HECMW_INPLEX_E_CPE4R,
  HECMW_INPLEX_E_CPE6,
  HECMW_INPLEX_E_CPE8,
  HECMW_INPLEX_E_CPE8R,
  HECMW_INPLEX_E_CPS3,
  HECMW_INPLEX_E_CPS4,
  HECMW_INPLEX_E_CPS4I,
  HECMW_INPLEX_E_CPS4R,
  HECMW_INPLEX_E_CPS6,
  HECMW_INPLEX_E_CPS8,
  HECMW_INPLEX_E_CPS8R,
  HECMW_INPLEX_E_DC1D2,
  HECMW_INPLEX_E_DC1D3,
  HECMW_INPLEX_E_DC2D3,
  HECMW_INPLEX_E_DC2D4,
  HECMW_INPLEX_E_DC2D6,
  HECMW_INPLEX_E_DC2D8,
  HECMW_INPLEX_E_DC3D4,
  HECMW_INPLEX_E_DC3D6,
  HECMW_INPLEX_E_DC3D8,
  HECMW_INPLEX_E_DC3D10,
  HECMW_INPLEX_E_DC3D15,
  HECMW_INPLEX_E_DC3D20,
  HECMW_INPLEX_E_DCAX3,
  HECMW_INPLEX_E_DCAX4,
  HECMW_INPLEX_E_DCAX6,
  HECMW_INPLEX_E_DCAX8,
  HECMW_INPLEX_E_DINTER4,
  HECMW_INPLEX_E_DINTER8,
  HECMW_INPLEX_E_DS4,
  HECMW_INPLEX_E_DS8,
  HECMW_INPLEX_E_INTER4,
  HECMW_INPLEX_E_INTER8,
  HECMW_INPLEX_E_S3R,
  HECMW_INPLEX_E_S4R,
  HECMW_INPLEX_E_S8R,
  HECMW_INPLEX_E_T3D2,
  HECMW_INPLEX_E_T3D3
};

extern double HECMW_inplex_get_number(void);

extern char *HECMW_inplex_get_text(void);

extern int HECMW_inplex_get_lineno(void);

extern int HECMW_inplex_next_token(void);

extern int HECMW_inplex_next_token_skip(int skip_token);

extern int HECMW_inplex_set_input(FILE *fp);

extern int HECMW_inplex_skip_line(void);

extern int HECMW_inplex_switch_to_include(const char *filename);

extern int HECMW_inplex_unput_token(void);

extern int HECMW_inplex_is_including(void);

#endif
