#define yy_create_buffer HECMW_ctrl_create_buffer
#define yy_delete_buffer HECMW_ctrl_delete_buffer
#define yy_scan_buffer HECMW_ctrl_scan_buffer
#define yy_scan_string HECMW_ctrl_scan_string
#define yy_scan_bytes HECMW_ctrl_scan_bytes
#define yy_flex_debug HECMW_ctrl_flex_debug
#define yy_init_buffer HECMW_ctrl_init_buffer
#define yy_flush_buffer HECMW_ctrl_flush_buffer
#define yy_load_buffer_state HECMW_ctrl_load_buffer_state
#define yy_switch_to_buffer HECMW_ctrl_switch_to_buffer
#define yyin HECMW_ctrlin
#define yyleng HECMW_ctrlleng
#define yylex HECMW_ctrllex
#define yyout HECMW_ctrlout
#define yyrestart HECMW_ctrlrestart
#define yytext HECMW_ctrltext
#define yywrap HECMW_ctrlwrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
static yyconst short int yy_accept[311] =
    {   0,
        0,    0,   65,   63,    2,    3,   63,   63,   63,   58,
       62,   60,   62,   59,   57,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   63,   63,    2,    3,    0,    0,    0,
        0,   60,   59,   62,   60,   59,   60,   62,   61,    0,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   30,   32,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,    0,    0,    0,    0,    0,    0,
        1,    0,    0,    0,    0,    0,   60,    0,    0,   62,
       60,   62,   61,   61,   61,   61,   61,   25,   61,   61,

       61,   61,   61,   61,   61,   61,   61,   39,   61,   61,
       61,   61,   36,   61,   61,   61,   61,   61,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   60,   61,   61,
       61,   61,   53,   61,   61,   61,   52,   61,   61,   61,
       61,   61,   61,   34,   61,   54,   61,   61,   61,   61,
       37,   61,    0,    0,    0,    0,    0,    0,    0,    7,
        0,    0,    0,   61,   61,   61,   61,   61,   61,   26,
       61,   61,   31,   61,   61,   40,   61,   38,   61,   61,
       61,   42,   43,    0,    0,    6,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   21,   23,   24,   50,   51,

       44,   61,   61,   27,   61,   61,   41,   61,   33,   61,
       61,   61,   61,    0,    0,    0,    0,    0,    0,   20,
       22,    0,   17,    0,    0,   11,   61,   56,   61,   61,
       61,   35,   55,   61,   61,   61,    0,   16,    0,    0,
       10,    5,    0,    0,    0,    0,   13,   61,   61,   61,
       61,   61,   61,   61,    4,    0,    0,    0,    0,   12,
        0,    0,    0,   45,   61,   61,   61,   49,   61,   61,
        0,    0,    0,    0,    0,    9,   28,   61,   61,   61,
       61,    0,    0,    8,    0,   15,   61,   61,   61,   61,
        0,   14,    0,   29,   61,   61,   61,    0,    0,   48,

       61,   61,    0,    0,   46,   47,    0,   19,   18,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    1,    7,    1,    1,    1,    1,    1,
        1,    1,    8,    9,   10,   11,   12,   13,   14,   15,
       13,   13,   13,   13,   13,   13,   13,   16,    1,    1,
       17,    1,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   27,   38,   39,   40,   27,
        1,   12,    1,    1,   41,    1,   27,   27,   27,   27,

       42,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       43,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[44] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        2,    2,    2,    2,    2,    3,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2
    } ;

static yyconst short int yy_base[315] =
    {   0,
        0,   38,  535, 1029,   44, 1029,  527,   27,   37, 1029,
       44,   52,    0,   57, 1029,   64,   66,   75,   77,   85,
       88,   96,  103,  105,  111,  121,  130,  118,  141,  133,
      153,  155,  161,  162,   50,   58, 1029,  498,  504,  500,
      490,  161,  175,    0,  165,  187,  191,  201,  206,  224,
      208,  229,  231,  216,  243,  246,  252,  255,  261,  270,
      277,  279,  287,  289,  295,  305,  311,  319,  325,  327,
      333,  335,  343,  346,  147,  487,  490,  483,  473,  155,
     1029,  191,   32,  466,  459,  467,  351,  366,  216,  355,
      369,  473,  374,  380,  383,  386,  392,  401,  404,  410,

      413,  420,  423,  429,  435,  437,  443,  389,  449,  451,
      457,  464,  466,  472,  474,  480,  488,  495,   68,  446,
      435,  438,  422,  424,  425,  224,  408,  374,  497,  503,
      505,  512,  521,  527,  530,  533,  539,  542,  545,  551,
      557,  559,  568,  570,  577,  583,  585,  591,  597,  606,
      608,  614,  402,  405,  405,  233,  391,  385,  381,   68,
      388,  350,  261,  620,  622,  630,  632,  640,  647,  649,
      655,  658,  667,  669,  675,  677,  684,  693,  695,  702,
      708,  716,  718,  343,  343,  104,  342,  328,  294,  321,
      326,  318,  299,  295,  290, 1029, 1029,  724,  726,  732,

      734,  740,  742,  749,  751,  758,  764,  770,  772,  779,
      781,  787,  793,  293,  298,  294,  280,  278,  268, 1029,
     1029,  274,  555,  265,  258, 1029,  796,  802,  804,  810,
      820,  822,  830,  833,  839,  845,  259,  645,  254,  247,
     1029, 1029,   65,  247,  226,  215, 1029,  847,  853,  855,
      862,  870,  873,  882, 1029,  173,  219,  218,  209, 1029,
      207,  199,  191,  884,  890,  892,  899,  901,  908,  916,
      184,  186,  176,  167,  145, 1029,  918,  925,  928,  931,
      939,  126,  118, 1029,  126, 1029,  946,  954,  960,  962,
      122, 1029,  122,  968,  971,  978,  980,  113,   92,  986,

      988,  994,   90,   80, 1001, 1007,   71, 1029, 1029, 1029,
       79, 1022, 1025,   77
    } ;

static yyconst short int yy_def[315] =
    {   0,
      310,    1,  310,  310,  310,  310,  310,  310,  310,  310,
      311,  311,  311,  311,  310,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  310,  313,  310,  310,  310,  310,  310,
      310,  310,  310,  311,  311,  311,  311,  311,  312,  314,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  313,  310,  310,  310,  310,  313,
      310,  313,  310,  310,  310,  310,  310,  310,  310,  311,
      311,  311,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  312,  312,  312,
      312,  312,  312,  312,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  312,  312,  312,  312,  312,  312,  312,
      310,  310,  310,  310,  310,  310,  312,  312,  312,  312,
      312,  310,  310,  310,  310,  310,  312,  312,  312,  312,
      310,  310,  310,  312,  312,  312,  312,  310,  310,  312,

      312,  312,  310,  310,  312,  312,  310,  310,  310,    0,
      310,  310,  310,  310
    } ;

static yyconst short int yy_nxt[1073] =
    {   0,
        4,    5,    6,    7,    5,    8,    4,    9,   10,   11,
       12,   13,   14,   14,   14,    4,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   25,   26,   27,
       28,   25,   25,   29,   30,   31,   32,   25,   25,   25,
       33,   25,   25,   34,   35,   36,   38,   42,   36,   43,
       43,   43,   81,   82,   45,   39,   46,   46,   46,   36,
       40,  123,   36,   41,   47,   47,   47,   45,  124,   46,
       46,   46,  192,   48,   44,   44,   44,   44,   92,   50,
       44,   50,   51,  244,   52,   44,   44,   44,   44,   53,
       50,  193,   50,   48,   55,   44,   44,  153,   44,   44,

       50,  245,   56,   50,  154,   54,   44,   44,  216,   58,
      309,   50,   57,   44,   44,   44,   44,   59,   50,  308,
       50,   44,   44,  307,   61,  304,   50,  217,   44,   44,
      303,   44,   44,   50,   62,   63,   50,   60,   64,  299,
       44,   44,  298,   44,   44,   50,  293,   66,   50,   81,
       82,   44,   44,  292,   69,  291,   50,   81,   82,   65,
       67,   68,   70,   44,   44,   44,   44,   75,   50,   71,
       50,   44,   44,   87,   87,   87,  310,   47,   47,   47,
      286,   76,   88,   72,   74,   42,   48,   43,   43,   43,
       77,  257,   73,   81,   82,   78,  285,   45,   79,   46,

       46,   46,   88,   47,   47,   47,   48,  284,   89,  258,
       90,  283,   48,   91,   91,   91,   44,   44,   44,   44,
      282,  310,  276,  310,  275,   93,   44,   44,  128,  128,
      128,  310,   48,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,  274,  310,  273,  310,  272,   94,  271,
       95,  263,   96,   44,   44,  262,   44,   44,  310,  161,
      162,  310,   44,   44,   44,   44,   44,  310,  187,  188,
      310,   44,   44,   99,  196,  197,  310,  261,   97,   98,
       44,   44,  260,  100,  259,  310,  255,   44,   44,   44,
       44,  101,  310,  247,  310,  246,  103,   44,   44,   44,

       44,  242,  310,  241,  310,   44,   44,  220,  221,  104,
      310,  240,  102,  239,  105,   44,   44,  217,  106,  238,
      310,   44,   44,  237,  108,  226,  310,  107,  225,   44,
       44,  111,  224,  109,  310,   44,   44,   44,   44,  110,
      310,  193,  310,   44,   44,   44,   44,  223,  310,  114,
      310,  222,  112,   44,   44,  219,   44,   44,  310,  218,
      113,  310,  116,   87,   87,   87,  115,   91,   91,   91,
      215,  118,   88,   89,  117,   89,  214,  195,  128,  128,
      128,   91,   91,   91,   44,   44,  128,  128,  128,  310,
       44,   44,   88,   44,   44,  310,   44,   44,  310,   44,

       44,  310,   44,   44,  310,  194,  129,  310,  191,  133,
      130,   44,   44,  131,   44,   44,  310,  132,  190,  310,
       44,   44,  134,   44,   44,  310,  189,  136,  310,  186,
       44,   44,  135,   44,   44,  310,  185,  184,  310,   44,
       44,  137,  138,  163,  310,   44,   44,   44,   44,  160,
      310,  139,  310,   44,   44,  159,  141,  158,  310,   44,
       44,   44,   44,  157,  310,  140,  310,   44,   44,  156,
      144,  143,  310,  142,   44,   44,   44,   44,  146,  310,
      155,  310,   44,   44,   44,   44,  145,  310,   50,  310,
       44,   44,  127,  126,  147,  310,  149,  148,   44,   44,

      125,  150,  122,  310,  121,   44,   44,   44,   44,  151,
      310,  120,  310,   44,   44,   44,   44,  119,  310,   86,
      310,   85,   44,   44,  165,   84,  166,  310,   83,   37,
      152,   44,   44,  164,  310,  310,  310,   44,   44,  167,
       44,   44,  310,   44,   44,  310,  168,  310,  310,   44,
       44,  169,   44,   44,  310,   44,   44,  310,  310,  243,
      310,   44,   44,  171,  170,  310,  310,   44,   44,   44,
       44,  310,  310,  244,  310,  310,  175,  310,   44,   44,
       44,   44,  172,  310,  310,  310,  173,   44,   44,  310,
      174,  245,  310,   44,   44,   44,   44,  176,  310,  310,

      310,   44,   44,  310,  178,  310,  310,   44,   44,  310,
      177,  310,  310,  310,  180,  310,   44,   44,   44,   44,
      179,  310,  310,  310,   44,   44,  310,  182,  183,  310,
       44,   44,   44,   44,  310,  310,  310,  310,  310,  181,
       44,   44,   44,   44,  199,  310,  310,  310,  310,  256,
       44,   44,  200,  201,  198,  310,  310,   44,   44,   44,
       44,  310,  310,  257,  310,   44,   44,  205,   44,   44,
      310,  310,  310,  310,  310,  202,  203,   44,   44,   44,
       44,  258,  310,  204,  310,   44,   44,   44,   44,  310,
      310,  310,  310,  310,   44,   44,  310,  310,  310,  310,

      206,  208,  207,   44,   44,   44,   44,  310,  310,  310,
      310,  310,   44,   44,  310,  310,  209,  310,   44,   44,
      310,  210,  310,  310,  310,  211,   44,   44,   44,   44,
      310,  310,  310,  310,   44,   44,   44,   44,  310,  310,
      310,  310,   44,   44,   44,   44,  310,  310,  310,  310,
       44,   44,   44,   44,  310,  310,  212,  310,  213,   44,
       44,   44,   44,  310,  310,  227,  310,  310,   44,   44,
      310,  229,  230,  310,   44,   44,  310,  228,  310,  310,
       44,   44,   44,   44,  310,  310,  310,  310,  231,   44,
       44,   44,   44,  310,  310,  310,  310,   44,   44,  232,

      233,  310,  310,   44,   44,  310,   44,   44,  310,  310,
      234,  310,   44,   44,   44,   44,  310,  310,  310,  310,
       44,   44,  235,  310,  310,  310,  248,  310,  236,  249,
       44,   44,   44,   44,  310,  310,  310,  310,  310,  250,
       44,   44,  310,   44,   44,  310,  310,  251,  310,   44,
       44,  310,  252,  310,  310,   44,   44,   44,   44,  310,
      310,  310,  310,   44,   44,   44,   44,  310,  310,  253,
      310,  310,   44,   44,  310,  254,  264,  310,  310,  267,
       44,   44,  310,   44,   44,  310,  310,  265,  310,  310,
      266,  268,   44,   44,   44,   44,  310,  310,  310,  310,

       44,   44,   44,   44,  310,  310,  310,  310,  310,   44,
       44,   44,   44,  269,  310,  310,  310,  278,   44,   44,
      310,  310,  270,  310,  310,  277,   44,   44,   44,   44,
      310,  310,  310,  310,  279,   44,   44,  310,   44,   44,
      310,   44,   44,  310,  280,  310,  310,  310,  310,   44,
       44,  310,  281,  288,  310,  310,   44,   44,  287,  310,
      289,  310,  310,  310,   44,   44,  310,  294,  290,  310,
       44,   44,   44,   44,  310,  310,  310,  310,   44,   44,
      310,   44,   44,  310,  295,  296,  310,  297,   44,   44,
       44,   44,  310,  310,  310,  310,   44,   44,   44,   44,

      300,  310,  305,  310,   44,   44,  310,  306,  310,  310,
      310,   44,   44,  301,  310,  302,  310,   44,   44,  310,
      310,  310,  310,   49,   49,   80,   80,   80,    3,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310
    } ;

static yyconst short int yy_chk[1073] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    2,    5,    8,    9,    5,    9,
        9,    9,   35,   35,   11,    8,   11,   11,   11,   36,
        8,   83,   36,    8,   12,   12,   12,   14,   83,   14,
       14,   14,  160,   12,   16,   16,   17,   17,  314,   16,
      311,   17,   16,  243,   17,   18,   18,   19,   19,   17,
       18,  160,   19,   12,   19,   20,   20,  119,   21,   21,

       20,  243,   19,   21,  119,   18,   22,   22,  186,   21,
      307,   22,   20,   23,   23,   24,   24,   22,   23,  304,
       24,   25,   25,  303,   23,  299,   25,  186,   28,   28,
      298,   26,   26,   28,   24,   24,   26,   22,   26,  293,
       27,   27,  291,   30,   30,   27,  285,   27,   30,   75,
       75,   29,   29,  283,   28,  282,   29,   80,   80,   26,
       27,   27,   29,   31,   31,   32,   32,   34,   31,   30,
       32,   33,   33,   42,   42,   42,   33,   45,   45,   45,
      275,   34,   42,   31,   32,   43,   45,   43,   43,   43,
       34,  256,   31,   82,   82,   34,  274,   46,   34,   46,

       46,   46,   42,   47,   47,   47,   45,  273,   48,  256,
       48,  272,   47,   48,   48,   48,   49,   49,   51,   51,
      271,   49,  263,   51,  262,   51,   54,   54,   89,   89,
       89,   54,   47,   50,   50,   50,   50,   50,   50,   52,
       52,   53,   53,  261,   52,  259,   53,  258,   52,  257,
       53,  246,   54,   55,   55,  245,   56,   56,   55,  126,
      126,   56,   57,   57,   50,   58,   58,   57,  156,  156,
       58,   59,   59,   57,  163,  163,   59,  244,   55,   56,
       60,   60,  240,   58,  239,   60,  237,   61,   61,   62,
       62,   59,   61,  225,   62,  224,   61,   63,   63,   64,

       64,  222,   63,  219,   64,   65,   65,  189,  189,   62,
       65,  218,   60,  217,   62,   66,   66,  216,   64,  215,
       66,   67,   67,  214,   65,  195,   67,   64,  194,   68,
       68,   67,  193,   66,   68,   69,   69,   70,   70,   66,
       69,  192,   70,   71,   71,   72,   72,  191,   71,   70,
       72,  190,   68,   73,   73,  188,   74,   74,   73,  187,
       69,   74,   72,   87,   87,   87,   71,   90,   90,   90,
      185,   74,   87,   88,   73,   88,  184,  162,   88,   88,
       88,   91,   91,   91,   93,   93,  128,  128,  128,   93,
       94,   94,   87,   95,   95,   94,   96,   96,   95,  108,

      108,   96,   97,   97,  108,  161,   93,   97,  159,   97,
       94,   98,   98,   95,   99,   99,   98,   96,  158,   99,
      100,  100,   98,  101,  101,  100,  157,  100,  101,  155,
      102,  102,   99,  103,  103,  102,  154,  153,  103,  104,
      104,  101,  102,  127,  104,  105,  105,  106,  106,  125,
      105,  103,  106,  107,  107,  124,  105,  123,  107,  109,
      109,  110,  110,  122,  109,  104,  110,  111,  111,  121,
      109,  107,  111,  106,  112,  112,  113,  113,  111,  112,
      120,  113,  114,  114,  115,  115,  110,  114,   92,  115,
      116,  116,   86,   85,  112,  116,  115,  114,  117,  117,

       84,  116,   79,  117,   78,  118,  118,  129,  129,  117,
      118,   77,  129,  130,  130,  131,  131,   76,  130,   41,
      131,   40,  132,  132,  130,   39,  131,  132,   38,    7,
      118,  133,  133,  129,    3,    0,  133,  134,  134,  132,
      135,  135,  134,  136,  136,  135,  134,    0,  136,  137,
      137,  135,  138,  138,  137,  139,  139,  138,    0,  223,
      139,  140,  140,  138,  136,    0,  140,  141,  141,  142,
      142,    0,  141,  223,  142,    0,  142,    0,  143,  143,
      144,  144,  139,  143,    0,  144,  140,  145,  145,    0,
      141,  223,  145,  146,  146,  147,  147,  143,  146,    0,

      147,  148,  148,    0,  147,    0,  148,  149,  149,    0,
      145,    0,  149,    0,  149,    0,  150,  150,  151,  151,
      148,  150,    0,  151,  152,  152,    0,  152,  152,  152,
      164,  164,  165,  165,    0,  164,    0,  165,    0,  150,
      166,  166,  167,  167,  165,  166,    0,  167,    0,  238,
      168,  168,  166,  167,  164,  168,    0,  169,  169,  170,
      170,    0,  169,  238,  170,  171,  171,  172,  172,  172,
      171,    0,    0,  172,    0,  168,  169,  173,  173,  174,
      174,  238,  173,  171,  174,  175,  175,  176,  176,    0,
      175,    0,  176,    0,  177,  177,    0,    0,    0,  177,

      174,  177,  175,  178,  178,  179,  179,    0,  178,    0,
      179,    0,  180,  180,    0,    0,  179,  180,  181,  181,
        0,  180,    0,  181,    0,  181,  182,  182,  183,  183,
        0,  182,    0,  183,  198,  198,  199,  199,    0,  198,
        0,  199,  200,  200,  201,  201,    0,  200,    0,  201,
      202,  202,  203,  203,    0,  202,  182,  203,  183,  204,
      204,  205,  205,    0,  204,  202,  205,    0,  206,  206,
        0,  205,  205,  206,  207,  207,    0,  203,    0,  207,
      208,  208,  209,  209,    0,  208,    0,  209,  206,  210,
      210,  211,  211,    0,  210,    0,  211,  212,  212,  208,

      210,    0,  212,  213,  213,    0,  227,  227,  213,    0,
      211,  227,  228,  228,  229,  229,    0,  228,    0,  229,
      230,  230,  212,    0,    0,  230,  227,    0,  213,  229,
      231,  231,  232,  232,    0,  231,    0,  232,    0,  230,
      233,  233,    0,  234,  234,  233,    0,  231,  234,  235,
      235,    0,  234,    0,  235,  236,  236,  248,  248,    0,
      236,    0,  248,  249,  249,  250,  250,    0,  249,  235,
      250,    0,  251,  251,    0,  236,  248,  251,    0,  251,
      252,  252,    0,  253,  253,  252,    0,  249,  253,    0,
      250,  252,  254,  254,  264,  264,    0,  254,    0,  264,

      265,  265,  266,  266,    0,  265,    0,  266,    0,  267,
      267,  268,  268,  253,  267,    0,  268,  266,  269,  269,
        0,    0,  254,  269,    0,  265,  270,  270,  277,  277,
        0,  270,    0,  277,  267,  278,  278,    0,  279,  279,
      278,  280,  280,  279,  269,    0,  280,    0,    0,  281,
      281,    0,  270,  279,  281,    0,  287,  287,  278,    0,
      280,  287,    0,    0,  288,  288,    0,  287,  281,  288,
      289,  289,  290,  290,    0,  289,    0,  290,  294,  294,
        0,  295,  295,  294,  288,  289,  295,  290,  296,  296,
      297,  297,    0,  296,    0,  297,  300,  300,  301,  301,

      295,  300,  301,  301,  302,  302,    0,  302,    0,  302,
        0,  305,  305,  296,    0,  297,  305,  306,  306,    0,
        0,    0,  306,  312,  312,  313,  313,  313,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "hecmw_ctrllex.l"
#define INITIAL 0
#line 2 "hecmw_ctrllex.l"
#include <string.h>
#include <errno.h>
#include "hecmw_ctrllex.h"
#include "hecmw_util.h"

typedef union {
	double dval;
	char *str;
} YYSTYPE;

static YYSTYPE yylval;
static int lineno;
static int flag_header;

static void set_flag_header(int flag);
#define YY_NO_UNPUT 1

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 30 "hecmw_ctrllex.l"



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 311 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1029 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 32 "hecmw_ctrllex.l"
{ lineno++; set_flag_header(0); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 33 "hecmw_ctrllex.l"
{ set_flag_header(0); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 34 "hecmw_ctrllex.l"
{ lineno++; set_flag_header(0); return HECMW_CTRLLEX_NL; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 36 "hecmw_ctrllex.l"
{ set_flag_header(1); return HECMW_CTRLLEX_H_CONTROL; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 37 "hecmw_ctrllex.l"
{ return flag_header ? HECMW_CTRLLEX_H_CONTROL : ' '; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 38 "hecmw_ctrllex.l"
{ set_flag_header(1); return HECMW_CTRLLEX_H_MESH; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 39 "hecmw_ctrllex.l"
{ return flag_header ? HECMW_CTRLLEX_H_MESH : ' '; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 40 "hecmw_ctrllex.l"
{ set_flag_header(1); return HECMW_CTRLLEX_H_MESH_GROUP; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 41 "hecmw_ctrllex.l"
{ return flag_header ? HECMW_CTRLLEX_H_MESH_GROUP : ' '; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 42 "hecmw_ctrllex.l"
{ set_flag_header(1); return HECMW_CTRLLEX_H_RESULT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 43 "hecmw_ctrllex.l"
{ return flag_header ? HECMW_CTRLLEX_H_RESULT : ' '; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 44 "hecmw_ctrllex.l"
{ set_flag_header(1); return HECMW_CTRLLEX_H_RESTART; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 45 "hecmw_ctrllex.l"
{ return flag_header ? HECMW_CTRLLEX_H_RESTART : ' '; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 46 "hecmw_ctrllex.l"
{ set_flag_header(1); return HECMW_CTRLLEX_H_COUPLE_UNIT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 47 "hecmw_ctrllex.l"
{ return flag_header ? HECMW_CTRLLEX_H_COUPLE_UNIT : ' '; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 48 "hecmw_ctrllex.l"
{ set_flag_header(1); return HECMW_CTRLLEX_H_COUPLE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 49 "hecmw_ctrllex.l"
{ return flag_header ? HECMW_CTRLLEX_H_COUPLE : ' '; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 50 "hecmw_ctrllex.l"
{ set_flag_header(1); return HECMW_CTRLLEX_H_COUPLE_BOUNDARY; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 51 "hecmw_ctrllex.l"
{ return flag_header ? HECMW_CTRLLEX_H_COUPLE_BOUNDARY : ' '; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 52 "hecmw_ctrllex.l"
{ set_flag_header(1); return HECMW_CTRLLEX_H_UNIT1; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 53 "hecmw_ctrllex.l"
{ return flag_header ? HECMW_CTRLLEX_H_UNIT1 : ' '; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 54 "hecmw_ctrllex.l"
{ set_flag_header(1); return HECMW_CTRLLEX_H_UNIT2; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 55 "hecmw_ctrllex.l"
{ return flag_header ? HECMW_CTRLLEX_H_UNIT2 : ' '; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 57 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_ABAQUS; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 58 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_DIR; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 59 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_FEMAP; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 60 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_GEOFEM; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 61 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_HECMW_DIST; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 62 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_HECMW_ENTIRE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 63 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_IN; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 64 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_INOUT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 65 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_IO; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 66 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_REFINE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 67 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_NAME; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 68 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_NASTRAN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 69 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_OUT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 70 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_TYPE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 71 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_NPROC; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 72 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_MXN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 73 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_MAXMN; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 74 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_MANUAL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 75 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_UNIT1; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 76 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_UNIT2; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 77 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_COUPLE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 78 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_DIRECTION; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 79 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_UNIT1_TO_UNIT2; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 80 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_UNIT2_TO_UNIT1; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 81 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_INTERPOLATION; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 82 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_TOLERANCE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 83 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_BBCOEF; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 84 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_BGCOEF; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 85 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_GEOM; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 86 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_DATA; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 87 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_NODE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 88 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_SURFACE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 89 "hecmw_ctrllex.l"
{ set_flag_header(0); return HECMW_CTRLLEX_K_ELEMENT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 92 "hecmw_ctrllex.l"
{ set_flag_header(0); return '='; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 93 "hecmw_ctrllex.l"
{ set_flag_header(0); return ','; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 95 "hecmw_ctrllex.l"
{
				yylval.dval = atof(yytext);
				set_flag_header(0);
				return HECMW_CTRLLEX_INT;
			}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 100 "hecmw_ctrllex.l"
{
				yylval.dval = atof(yytext);
				set_flag_header(0);
				return HECMW_CTRLLEX_DOUBLE;
			}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 105 "hecmw_ctrllex.l"
{
				yylval.str = yytext;
				set_flag_header(0);
				return HECMW_CTRLLEX_NAME;
			}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 110 "hecmw_ctrllex.l"
{
				yylval.str = yytext;
				set_flag_header(0);
				return HECMW_CTRLLEX_FILENAME;
			}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 115 "hecmw_ctrllex.l"
{ set_flag_header(0); return yytext[0]; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 116 "hecmw_ctrllex.l"
{ return 0; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 118 "hecmw_ctrllex.l"
ECHO;
	YY_BREAK

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 311 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 311 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 310);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 118 "hecmw_ctrllex.l"


static void
set_flag_header(int flag)
{
	flag_header = flag ? 1 : 0;
}


int
HECMW_ctrllex_get_lineno(void)
{
	return lineno;
}


double
HECMW_ctrllex_get_number(void)
{
	return yylval.dval;
}


char *
HECMW_ctrllex_get_text(void)
{
	return yytext;
}


int
HECMW_ctrllex_next_token(void)
{
	return yylex();
}


int
HECMW_ctrllex_next_token_skip(int skip_token)
{
	int token;
	while((token = yylex())) {
		if(token != skip_token) break;
	}
	return token;
}


int
HECMW_ctrllex_set_input(FILE *fp)
{
	static int first = 1;
	if(fp == NULL) return -1;
	if(first) {
		yyin = fp;
		first = 0;
	} else {
		yyrestart(fp);
	}
	lineno = 1;
	return 0;
}


int
HECMW_ctrllex_skip_line(void)
{
	int token;
	while((token = HECMW_ctrllex_next_token())) {
		if(token == HECMW_CTRLLEX_NL) break;
	}
	return token;
}


int
HECMW_ctrllex_unput_token(void)
{
	char *p = yytext;
	while(*p) {
		if(*p == '\n') {
			lineno--;
		}
		p++;
	}
	yyless(0);
	return 0;
}


int
HECMW_ctrlwrap(void)
{
	return 1;
}


