 :========================================:
 :**   BEGIN FSTR Structural Analysis   **:
 :========================================:
         Total no. of processors:  1



  *    STAGE Initialization and input   **



  ***   STAGE Eigenvalue analysis     **

  ****   STAGE Stiffness Matrix assembly  **
 *-------------------------------------------*
 NOTE: Loads ignored for eigenvalue analysis.
 *-------------------------------------------*
 ####fstr_AddBC finished
 fstr_mat_ass: OK

  ****   STAGE Mass   assembly           **
 +===================+
 Total mass:  8.010000716149888E-9
 +===================+

  *****   STAGE Begin Lanczos loop     **

  *     STAGE Output and postprocessing    **
 
 *----------------------------------------------*
 *--E I G E N V A L U E  C O N V E R G E N C E--*
 *----------------------------------------------*
 Absolute residual =  |(||Kx - lambda*Mx||)|
 *------------- Residual Check ----------------*
    Iter.#   Eigenvalue    Abs. Residual  
    *-----*  *---------*  *--------------*
     19     0.513275E+09   0.323750E-08
     18     0.513275E+09   0.209385E-08
     17     0.181452E+11   0.333081E-07
 
 *    ---END Eigenvalue listing---     *
 

 hecmw_update_3_R: OK
 fstr_output3d: OK

 hecmw_update_3_R: OK
 fstr_output3d: OK

 hecmw_update_3_R: OK
 fstr_output3d: OK



 :========================================:
 :**            END of FSTR             **:
 :========================================:
